// Lucide "bitcoin" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideBitcoin: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.4903 0.7954C0.6955 0.8315 0.7461 0.5443 0.541 0.5081M0.4903 0.7954L0.2442 0.752M0.4903 0.7954L0.4759 0.8775M0.541 0.5081C0.7462 0.5443 0.7968 0.2571 0.5916 0.2209M0.541 0.5081L0.3768 0.4792M0.5916 0.2209L0.3454 0.1775M0.5916 0.2209L0.6061 0.1388M0.3117 0.8485L0.4419 0.1099",
    ),
    o,
  ),
];
