// Lucide "book-dashed" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideBookDashed: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.7083L0.5625 0.7083"), o),
  g.path(P("M0.5 0.9167L0.5625 0.9167"), o),
  g.path(P("M0.5 0.0833L0.5625 0.0833"), o),
  g.path(
    P("M0.7292 0.9167L0.7917 0.9167C0.8147 0.9167 0.8333 0.898 0.8333 0.875"),
    o,
  ),
  g.path(
    P(
      "M0.7292 0.0833L0.7917 0.0833C0.8147 0.0833 0.8333 0.102 0.8333 0.125L0.8333 0.1875",
    ),
    o,
  ),
  g.path(P("M0.8333 0.5833L0.8333 0.7083 0.7292 0.7083"), o),
  g.path(P("M0.8333 0.3542L0.8333 0.4167"), o),
  g.path(P("M0.1667 0.4167L0.1667 0.3542"), o),
  g.path(P("M0.1667 0.8125L0.1667 0.5833"), o),
  g.path(
    P("M0.1667 0.1875C0.1667 0.13 0.2133 0.0833 0.2708 0.0833L0.3333 0.0833"),
    o,
  ),
  g.path(
    P(
      "M0.3333 0.9167L0.2708 0.9167C0.2133 0.9167 0.1667 0.87 0.1667 0.8125 0.1667 0.755 0.2133 0.7083 0.2708 0.7083L0.3333 0.7083",
    ),
    o,
  ),
];
