// Lucide "circle-slash" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCircleSlash: IconDrawing = ({ g, o, X, Y, S }) => [
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
  g.line(X(0.375), Y(0.625), X(0.625), Y(0.375), o),
];
