// Lucide "diff" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideDiff: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.125L0.5 0.7083"), o),
  g.path(P("M0.2083 0.4167L0.7917 0.4167"), o),
  g.path(P("M0.2083 0.875L0.7917 0.875"), o),
];
