// Lucide "flag-triangle-right" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideFlagTriangleRight: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.25 0.9167L0.25 0.1167C0.25 0.105 0.2561 0.0942 0.266 0.0881 0.276 0.0821 0.2884 0.0817 0.2988 0.0871L0.7729 0.3242C0.7844 0.3297 0.7917 0.3414 0.7917 0.3542 0.7917 0.3669 0.7844 0.3786 0.7729 0.3842L0.25 0.6458",
    ),
    o,
  ),
];
