// Lucide "git-pull-request" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideGitPullRequest: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.75), Y(0.75), S(0.25), o),
  g.circle(X(0.25), Y(0.25), S(0.25), o),
  g.path(
    P(
      "M0.5417 0.25L0.6667 0.25C0.7127 0.25 0.75 0.2873 0.75 0.3333L0.75 0.625",
    ),
    o,
  ),
  g.line(X(0.25), Y(0.375), X(0.25), Y(0.875), o),
];
