// Lucide "git-pull-request-closed" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideGitPullRequestClosed: IconDrawing = ({
  g,
  o,
  X,
  Y,
  S,
  P,
}) => [
  g.path(P("M0.6458 0.1458L0.8542 0.3542"), o),
  g.path(P("M0.6458 0.3542L0.8542 0.1458"), o),
  g.path(P("M0.75 0.4842L0.75 0.625"), o),
  g.path(P("M0.25 0.375L0.25 0.875"), o),
  g.circle(X(0.75), Y(0.75), S(0.25), o),
  g.circle(X(0.25), Y(0.25), S(0.25), o),
];
