// Lucide "git-merge-conflict" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideGitMergeConflict: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(
    P("M0.5 0.25L0.6667 0.25C0.7127 0.25 0.75 0.2873 0.75 0.3333L0.75 0.625"),
    o,
  ),
  g.path(P("M0.25 0.5L0.25 0.875"), o),
  g.path(P("M0.3542 0.1458L0.1458 0.3542"), o),
  g.path(P("M0.3542 0.3542L0.1458 0.1458"), o),
  g.circle(X(0.75), Y(0.75), S(0.25), o),
];
