// Lucide "git-branch-minus" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideGitBranchMinus: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.625 0.25C0.4179 0.25 0.25 0.4179 0.25 0.625L0.25 0.125"), o),
  g.path(P("M0.875 0.75L0.625 0.75"), o),
  g.circle(X(0.75), Y(0.25), S(0.25), o),
  g.circle(X(0.25), Y(0.75), S(0.25), o),
];
