// Lucide "git-fork" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideGitFork: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.75), S(0.25), o),
  g.circle(X(0.25), Y(0.25), S(0.25), o),
  g.circle(X(0.75), Y(0.25), S(0.25), o),
  g.path(
    P(
      "M0.75 0.375L0.75 0.4583C0.75 0.4833 0.7333 0.5 0.7083 0.5L0.2917 0.5C0.2667 0.5 0.25 0.4833 0.25 0.4583L0.25 0.375",
    ),
    o,
  ),
  g.path(P("M0.5 0.5L0.5 0.625"), o),
];
