// Lucide "git-graph" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideGitGraph: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.2083), Y(0.25), S(0.25), o),
  g.path(P("M0.2083 0.375L0.2083 0.625"), o),
  g.circle(X(0.2083), Y(0.75), S(0.25), o),
  g.path(P("M0.5 0.125L0.5 0.875"), o),
  g.circle(X(0.7917), Y(0.25), S(0.25), o),
  g.path(P("M0.6667 0.6542C0.7461 0.5831 0.7916 0.4816 0.7917 0.375"), o),
];
