// Lucide "lambda" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideLambda: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.4742 0.4167L0.2083 0.8333"), o),
  g.path(
    P(
      "M0.7917 0.75C0.7917 0.796 0.7544 0.8333 0.7083 0.8333 0.5054 0.8332 0.4978 0.1667 0.2917 0.1667 0.2456 0.1667 0.2083 0.204 0.2083 0.25",
    ),
    o,
  ),
];
