// Lucide "line-dot-left-horizontal" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideLineDotLeftHorizontal: IconDrawing = ({
  g,
  o,
  X,
  Y,
  S,
  P,
}) => [
  g.path(P("M0.375 0.5L0.875 0.5"), o),
  g.circle(X(0.25), Y(0.5), S(0.25), o),
];
