// Lucide "line-dot-top-vertical" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideLineDotTopVertical: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.5 0.375L0.5 0.875"), o),
  g.circle(X(0.5), Y(0.25), S(0.25), o),
];
