// Lucide "merge" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMerge: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.3333 0.25L0.5 0.0833 0.6667 0.25"), o),
  g.path(
    P(
      "M0.5 0.0833L0.5 0.5125C0.5005 0.5573 0.4829 0.6005 0.4512 0.6322L0.1667 0.9167",
    ),
    o,
  ),
  g.path(P("M0.8333 0.9167L0.625 0.7083"), o),
];
