// Lucide "option" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideOption: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5833 0.125L0.875 0.125"), o),
  g.path(
    P(
      "M0.125 0.125L0.345 0.125C0.3629 0.125 0.3788 0.1365 0.3845 0.1535L0.6155 0.8465C0.6212 0.8635 0.6371 0.875 0.655 0.875L0.875 0.875",
    ),
    o,
  ),
];
