// Lucide "pi" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucidePi: IconDrawing = ({ g, o, X, Y, P }) => [
  g.line(X(0.375), Y(0.1667), X(0.375), Y(0.8333), o),
  g.path(
    P("M0.1667 0.2917C0.1667 0.2208 0.2208 0.1667 0.2917 0.1667L0.8333 0.1667"),
    o,
  ),
  g.path(
    P("M0.75 0.8333C0.6792 0.8333 0.625 0.7792 0.625 0.7083L0.625 0.1667"),
    o,
  ),
];
