// Lucide "radical" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideRadical: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.125 0.5L0.2617 0.5C0.2796 0.5 0.2955 0.5115 0.3012 0.5285L0.3969 0.8591C0.3999 0.8679 0.4083 0.8736 0.4176 0.8732 0.4269 0.8728 0.4348 0.8663 0.4369 0.8572L0.5758 0.1988C0.5803 0.18 0.597 0.1667 0.6163 0.1667L0.875 0.1667",
    ),
    o,
  ),
];
