// Lucide "rectangle-circle" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideRectangleCircle: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(
    P(
      "M0.5833 0.1667L0.5833 0.8333 0.125 0.8333C0.102 0.8333 0.0833 0.8147 0.0833 0.7917L0.0833 0.2083C0.0833 0.1853 0.102 0.1667 0.125 0.1667Z",
    ),
    o,
  ),
  g.circle(X(0.5833), Y(0.5), S(0.6667), o),
];
