// Lucide "rss" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideRss: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.1667 0.4583C0.3738 0.4583 0.5417 0.6262 0.5417 0.8333"), o),
  g.path(P("M0.1667 0.1667C0.5349 0.1667 0.8333 0.4651 0.8333 0.8333"), o),
  g.circle(X(0.2083), Y(0.7917), S(0.0833), o),
];
