// Lucide "slash" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSlash: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.9167 0.0833L0.0833 0.9167"), o),
];
