// Lucide "split" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSplit: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.6667 0.125L0.875 0.125 0.875 0.3333"), o),
  g.path(P("M0.3333 0.125L0.125 0.125 0.125 0.3333"), o),
  g.path(
    P(
      "M0.5 0.9167L0.5 0.5708C0.5005 0.526 0.4829 0.4829 0.4512 0.4512L0.125 0.125",
    ),
    o,
  ),
  g.path(P("M0.625 0.375L0.875 0.125"), o),
];
