// Lucide "webhook-off" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideWebhookOff: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.7083 0.7083L0.5 0.7083C0.4546 0.7075 0.4192 0.7467 0.3958 0.7875 0.351 0.8672 0.2499 0.8955 0.1702 0.8506 0.0905 0.8058 0.0622 0.7047 0.1071 0.625",
    ),
    o,
  ),
  g.path(
    P(
      "M0.375 0.1417C0.4105 0.1005 0.4639 0.0792 0.518 0.0847 0.5721 0.0902 0.6201 0.1217 0.6467 0.1692",
    ),
    o,
  ),
  g.path(
    P("M0.25 0.7083L0.3792 0.4667C0.3921 0.4398 0.393 0.4088 0.3815 0.3812"),
    o,
  ),
  g.path(P("M0.8458 0.8458C0.8176 0.8652 0.7842 0.8753 0.75 0.875"), o),
  g.path(P("M0.775 0.5417C0.848 0.5529 0.9049 0.6107 0.9149 0.6839"), o),
  g.path(P("M0.5 0.25L0.525 0.2917"), o),
  g.path(P("M0.0833 0.0833L0.9167 0.9167"), o),
];
