// Lucide "beaker" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideBeaker: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.1875 0.125L0.8125 0.125"), o),
  g.path(
    P(
      "M0.25 0.125L0.25 0.7917C0.25 0.8377 0.2873 0.875 0.3333 0.875L0.6667 0.875C0.7127 0.875 0.75 0.8377 0.75 0.7917L0.75 0.125",
    ),
    o,
  ),
  g.path(P("M0.25 0.5833L0.75 0.5833"), o),
];
