// Lucide "eclipse" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideEclipse: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
  g.path(
    P(
      "M0.5 0.0833C0.4256 0.1578 0.3965 0.2662 0.4237 0.3679 0.451 0.4696 0.5304 0.549 0.6321 0.5763 0.7338 0.6035 0.8422 0.5744 0.9167 0.5",
    ),
    o,
  ),
];
