// Lucide "mirror-round" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMirrorRound: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.4167 0.275L0.3583 0.3333"), o),
  g.path(P("M0.5 0.75L0.5 0.9167"), o),
  g.path(P("M0.625 0.3125L0.3958 0.5417"), o),
  g.path(P("M0.2917 0.9167L0.7083 0.9167"), o),
  g.circle(X(0.5), Y(0.4167), S(0.6667), o),
];
