// Lucide "telescope" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTelescope: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(
    P(
      "M0.4194 0.5205L0.1619 0.5755C0.1411 0.58 0.1205 0.5669 0.1157 0.5462L0.0933 0.4566C0.0879 0.4343 0.1004 0.4114 0.1221 0.4039L0.6848 0.2189",
    ),
    o,
  ),
  g.path(P("M0.565 0.4895L0.7455 0.451"), o),
  g.path(P("M0.6667 0.875L0.5373 0.6162"), o),
  g.path(
    P(
      "M0.6869 0.2475C0.6757 0.2029 0.7029 0.1576 0.7475 0.1465L0.7929 0.1351C0.8152 0.1296 0.8378 0.1431 0.8434 0.1654L0.9065 0.4179C0.9121 0.4402 0.8986 0.4629 0.8762 0.4685L0.8308 0.4798C0.7862 0.4909 0.741 0.4638 0.7298 0.4192Z",
    ),
    o,
  ),
  g.path(P("M0.2566 0.3597L0.303 0.5454"), o),
  g.path(P("M0.3333 0.875L0.4627 0.6162"), o),
  g.circle(X(0.5), Y(0.5417), S(0.1667), o),
];
