// Lucide "test-tube-diagonal" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTestTubeDiagonal: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.875 0.2917L0.2842 0.8825C0.2381 0.9281 0.1638 0.9279 0.1179 0.8821 0.0719 0.836 0.0719 0.7615 0.1179 0.7154L0.7083 0.125",
    ),
    o,
  ),
  g.path(P("M0.6667 0.0833L0.9167 0.3333"), o),
  g.path(P("M0.5 0.6667L0.1667 0.6667"), o),
];
