// Lucide "test-tube" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTestTube: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.6042 0.0833L0.6042 0.8125C0.6042 0.8708 0.5583 0.9167 0.5 0.9167 0.4417 0.9167 0.3958 0.8708 0.3958 0.8125L0.3958 0.0833",
    ),
    o,
  ),
  g.path(P("M0.3542 0.0833L0.6458 0.0833"), o),
  g.path(P("M0.6042 0.6667L0.3958 0.6667"), o),
];
