// Lucide "chart-candlestick" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideChartCandlestick: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.375 0.2083L0.375 0.375"), o),
  g.path(
    P(
      "M0.3333 0.375L0.4167 0.375Q0.4583 0.375 0.4583 0.4167L0.4583 0.5833Q0.4583 0.625 0.4167 0.625L0.3333 0.625Q0.2917 0.625 0.2917 0.5833L0.2917 0.4167Q0.2917 0.375 0.3333 0.375Z",
    ),
    o,
  ),
  g.path(P("M0.375 0.625L0.375 0.7083"), o),
  g.path(P("M0.7083 0.125L0.7083 0.2083"), o),
  g.path(
    P(
      "M0.6667 0.2083L0.75 0.2083Q0.7917 0.2083 0.7917 0.25L0.7917 0.5Q0.7917 0.5417 0.75 0.5417L0.6667 0.5417Q0.625 0.5417 0.625 0.5L0.625 0.25Q0.625 0.2083 0.6667 0.2083Z",
    ),
    o,
  ),
  g.path(P("M0.7083 0.5417L0.7083 0.6667"), o),
  g.path(
    P(
      "M0.125 0.125L0.125 0.7917C0.125 0.8377 0.1623 0.875 0.2083 0.875L0.875 0.875",
    ),
    o,
  ),
];
