// Lucide "chart-scatter" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideChartScatter: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.3125), Y(0.3125), S(0.0417), o),
  g.circle(X(0.7708), Y(0.2292), S(0.0417), o),
  g.circle(X(0.4792), Y(0.4792), S(0.0417), o),
  g.circle(X(0.3125), Y(0.6875), S(0.0417), o),
  g.circle(X(0.7292), Y(0.6042), S(0.0417), o),
  g.path(
    P(
      "M0.125 0.125L0.125 0.7917C0.125 0.8377 0.1623 0.875 0.2083 0.875L0.875 0.875",
    ),
    o,
  ),
];
