// Lucide "chart-bar-increasing" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideChartBarIncreasing: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.125 0.125L0.125 0.7917C0.125 0.8377 0.1623 0.875 0.2083 0.875L0.875 0.875",
    ),
    o,
  ),
  g.path(P("M0.2917 0.4583L0.625 0.4583"), o),
  g.path(P("M0.2917 0.6667L0.7917 0.6667"), o),
  g.path(P("M0.2917 0.25L0.4167 0.25"), o),
];
