// Lucide "chart-no-axes-column-increasing" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideChartNoAxesColumnIncreasing: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.2083 0.875L0.2083 0.625"), o),
  g.path(P("M0.5 0.875L0.5 0.375"), o),
  g.path(P("M0.7917 0.875L0.7917 0.125"), o),
];
