// Lucide "chart-no-axes-gantt" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideChartNoAxesGantt: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.25 0.2083L0.75 0.2083"), o),
  g.path(P("M0.1667 0.5L0.5833 0.5"), o),
  g.path(P("M0.5 0.7917L0.8333 0.7917"), o),
];
