// Lucide "kanban" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideKanban: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.2083 0.125L0.2083 0.7083"), o),
  g.path(P("M0.5 0.125L0.5 0.4583"), o),
  g.path(P("M0.7917 0.125L0.7917 0.875"), o),
];
