// Lucide "trending-down" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTrendingDown: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.6667 0.7083L0.9167 0.7083 0.9167 0.4583"), o),
  g.path(P("M0.9167 0.7083L0.5625 0.3542 0.3542 0.5625 0.0833 0.2917"), o),
];
