// Lucide "trending-up-down" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTrendingUpDown: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.6178 0.6178L0.875 0.875"), o),
  g.path(P("M0.875 0.6667L0.875 0.875 0.6667 0.875"), o),
  g.path(P("M0.875 0.125L0.5 0.5 0.3333 0.3333 0.0833 0.5833"), o),
  g.path(P("M0.875 0.3333L0.875 0.125 0.6667 0.125"), o),
];
