// Lucide "trending-up" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTrendingUp: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.6667 0.2917L0.9167 0.2917 0.9167 0.5417"), o),
  g.path(P("M0.9167 0.2917L0.5625 0.6458 0.3542 0.4375 0.0833 0.7083"), o),
];
