// Lucide "alarm-clock-check" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideAlarmClockCheck: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.5417), S(0.6667), o),
  g.path(P("M0.2083 0.125L0.0833 0.25"), o),
  g.path(P("M0.9167 0.25L0.7917 0.125"), o),
  g.path(P("M0.2658 0.7792L0.1667 0.875"), o),
  g.path(P("M0.735 0.7779L0.8333 0.875"), o),
  g.path(P("M0.375 0.5417L0.4583 0.625 0.625 0.4583"), o),
];
