// Lucide "disc-3" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideDisc3: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
  g.path(P("M0.25 0.5C0.25 0.4292 0.2792 0.3667 0.325 0.325"), o),
  g.circle(X(0.5), Y(0.5), S(0.1667), o),
  g.path(P("M0.75 0.5C0.75 0.5708 0.7208 0.6333 0.675 0.675"), o),
];
