// Lucide "laptop-minimal" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideLaptopMinimal: IconDrawing = ({ g, o, X, Y, P }) => [
  g.path(
    P(
      "M0.2083 0.1667L0.7917 0.1667Q0.875 0.1667 0.875 0.25L0.875 0.5833Q0.875 0.6667 0.7917 0.6667L0.2083 0.6667Q0.125 0.6667 0.125 0.5833L0.125 0.25Q0.125 0.1667 0.2083 0.1667Z",
    ),
    o,
  ),
  g.line(X(0.0833), Y(0.8333), X(0.9167), Y(0.8333), o),
];
