// Lucide "memory-stick" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMemoryStick: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.5L0.5 0.4167"), o),
  g.path(P("M0.5 0.75L0.5 0.6667"), o),
  g.path(P("M0.6667 0.5L0.6667 0.4167"), o),
  g.path(P("M0.6667 0.75L0.6667 0.6667"), o),
  g.path(P("M0.0833 0.4583L0.1458 0.4583"), o),
  g.path(P("M0.8333 0.75L0.8333 0.6667"), o),
  g.path(P("M0.8542 0.4583L0.9167 0.4583"), o),
  g.path(P("M0.1667 0.75L0.1667 0.6667"), o),
  g.path(P("M0.3333 0.5L0.3333 0.4167"), o),
  g.path(P("M0.3333 0.75L0.3333 0.6667"), o),
  g.path(
    P(
      "M0.1667 0.25L0.8333 0.25Q0.9167 0.25 0.9167 0.3333L0.9167 0.5833Q0.9167 0.6667 0.8333 0.6667L0.1667 0.6667Q0.0833 0.6667 0.0833 0.5833L0.0833 0.3333Q0.0833 0.25 0.1667 0.25Z",
    ),
    o,
  ),
];
