// Lucide "mic-off" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMicOff: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.7917L0.5 0.9167"), o),
  g.path(
    P(
      "M0.625 0.3892L0.625 0.2083C0.6247 0.1506 0.5848 0.1006 0.5285 0.0874 0.4722 0.0742 0.4143 0.1013 0.3883 0.1529",
    ),
    o,
  ),
  g.path(
    P(
      "M0.7062 0.7062C0.6228 0.7897 0.4974 0.8146 0.3884 0.7695 0.2794 0.7243 0.2083 0.618 0.2083 0.5L0.2083 0.4167",
    ),
    o,
  ),
  g.path(
    P("M0.7871 0.5513C0.7901 0.5343 0.7917 0.5172 0.7917 0.5L0.7917 0.4167"),
    o,
  ),
  g.path(P("M0.0833 0.0833L0.9167 0.9167"), o),
  g.path(
    P(
      "M0.375 0.375L0.375 0.5C0.375 0.5505 0.4055 0.5961 0.4522 0.6154 0.4989 0.6347 0.5526 0.624 0.5883 0.5883",
    ),
    o,
  ),
];
