// Lucide "tablet" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTablet: IconDrawing = ({ g, o, X, Y, P }) => [
  g.path(
    P(
      "M0.25 0.0833L0.75 0.0833Q0.8333 0.0833 0.8333 0.1667L0.8333 0.8333Q0.8333 0.9167 0.75 0.9167L0.25 0.9167Q0.1667 0.9167 0.1667 0.8333L0.1667 0.1667Q0.1667 0.0833 0.25 0.0833Z",
    ),
    o,
  ),
  g.line(X(0.5), Y(0.75), X(0.5004), Y(0.75), o),
];
