// Lucide "tv-minimal" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTvMinimal: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.2917 0.875L0.7083 0.875"), o),
  g.path(
    P(
      "M0.1667 0.125L0.8333 0.125Q0.9167 0.125 0.9167 0.2083L0.9167 0.625Q0.9167 0.7083 0.8333 0.7083L0.1667 0.7083Q0.0833 0.7083 0.0833 0.625L0.0833 0.2083Q0.0833 0.125 0.1667 0.125Z",
    ),
    o,
  ),
];
