// Lucide "usb-c-port" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideUsbCPort: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.25 0.5L0.75 0.5"), o),
  g.path(
    P(
      "M0.25 0.3333L0.75 0.3333Q0.9167 0.3333 0.9167 0.5L0.9167 0.5Q0.9167 0.6667 0.75 0.6667L0.25 0.6667Q0.0833 0.6667 0.0833 0.5L0.0833 0.5Q0.0833 0.3333 0.25 0.3333Z",
    ),
    o,
  ),
];
