// Lucide "usb" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideUsb: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.4167), Y(0.2917), S(0.0833), o),
  g.circle(X(0.1667), Y(0.8333), S(0.0833), o),
  g.path(P("M0.1958 0.8042L0.7917 0.2083"), o),
  g.path(P("M0.875 0.125L0.75 0.1667 0.8333 0.25Z"), o),
  g.path(P("M0.3858 0.32L0.2083 0.5 0.2917 0.7083"), o),
  g.path(P("M0.4167 0.5833L0.625 0.6667 0.7708 0.5208"), o),
  g.path(P("M0.75 0.5L0.7917 0.4583 0.8333 0.5 0.7917 0.5417Z"), o),
];
