// Lucide "circle-question-mark" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCircleQuestionMark: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
  g.path(
    P(
      "M0.3787 0.375C0.399 0.3175 0.4577 0.283 0.5178 0.2933 0.5779 0.3036 0.6218 0.3557 0.6217 0.4167 0.6217 0.5 0.4967 0.5417 0.4967 0.5417",
    ),
    o,
  ),
  g.path(P("M0.5 0.7083L0.5004 0.7083"), o),
];
