// Lucide "person-standing" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucidePersonStanding: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.2083), S(0.0833), o),
  g.path(P("M0.375 0.8333L0.5 0.5833 0.625 0.8333"), o),
  g.path(P("M0.25 0.3333L0.5 0.4167 0.75 0.3333"), o),
  g.path(P("M0.5 0.4167L0.5 0.5833"), o),
];
