// Lucide "sun-medium" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSunMedium: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.5), S(0.3333), o),
  g.path(P("M0.5 0.125L0.5 0.1667"), o),
  g.path(P("M0.5 0.8333L0.5 0.875"), o),
  g.path(P("M0.125 0.5L0.1667 0.5"), o),
  g.path(P("M0.8333 0.5L0.875 0.5"), o),
  g.path(P("M0.7652 0.2348L0.7357 0.2643"), o),
  g.path(P("M0.2643 0.7357L0.2348 0.7652"), o),
  g.path(P("M0.2348 0.2348L0.2643 0.2643"), o),
  g.path(P("M0.7357 0.7357L0.7652 0.7652"), o),
];
