// Lucide "zoom-in" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideZoomIn: IconDrawing = ({ g, o, X, Y, S }) => [
  g.circle(X(0.4583), Y(0.4583), S(0.6667), o),
  g.line(X(0.875), Y(0.875), X(0.6937), Y(0.6937), o),
  g.line(X(0.4583), Y(0.3333), X(0.4583), Y(0.5833), o),
  g.line(X(0.3333), Y(0.4583), X(0.5833), Y(0.4583), o),
];
