// Lucide "face-slightly-smiling" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideFaceSlightlySmiling: IconDrawing = ({
  g,
  o,
  X,
  Y,
  S,
  P,
}) => [
  g.path(P("M0.625 0.4167L0.625 0.375"), o),
  g.path(
    P(
      "M0.6863 0.625C0.6389 0.678 0.5711 0.7083 0.5 0.7083 0.4289 0.7083 0.3611 0.678 0.3137 0.625",
    ),
    o,
  ),
  g.path(P("M0.375 0.4167L0.375 0.375"), o),
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
];
