// Lucide "face-expressionless" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideFaceExpressionless: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.5833 0.4167L0.6667 0.4167"), o),
  g.path(P("M0.3333 0.4167L0.4167 0.4167"), o),
  g.path(P("M0.3333 0.6667L0.6667 0.6667"), o),
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
];
