// Lucide "anchor" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideAnchor: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.5 0.25L0.5 0.9167"), o),
  g.path(
    P(
      "M0.7917 0.5417L0.875 0.5C0.875 0.7071 0.7071 0.875 0.5 0.875 0.2929 0.875 0.125 0.7071 0.125 0.5L0.2083 0.5417",
    ),
    o,
  ),
  g.path(P("M0.375 0.4583L0.625 0.4583"), o),
  g.circle(X(0.5), Y(0.1667), S(0.1667), o),
];
