// Lucide "circle-parking" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCircleParking: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
  g.path(
    P(
      "M0.375 0.7083L0.375 0.2917 0.5417 0.2917C0.6107 0.2917 0.6667 0.3476 0.6667 0.4167 0.6667 0.4857 0.6107 0.5417 0.5417 0.5417L0.375 0.5417",
    ),
    o,
  ),
];
