// Lucide "gauge" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideGauge: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.5833L0.6667 0.4167"), o),
  g.path(
    P(
      "M0.1392 0.7917C0.0381 0.6166 0.0773 0.3941 0.2322 0.2641 0.3871 0.1342 0.6129 0.1342 0.7678 0.2641 0.9227 0.3941 0.9619 0.6166 0.8608 0.7917",
    ),
    o,
  ),
];
