// Lucide "tractor" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTractor: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(
    P(
      "M0.4167 0.4583L0.875 0.4958C0.8964 0.5 0.9109 0.52 0.9083 0.5417L0.8806 0.7149C0.8774 0.7351 0.8599 0.75 0.8395 0.75L0.8333 0.75",
    ),
    o,
  ),
  g.path(P("M0.6667 0.75L0.4583 0.75"), o),
  g.path(
    P("M0.75 0.2083C0.727 0.2083 0.7083 0.227 0.7083 0.25L0.7083 0.4822"),
    o,
  ),
  g.path(
    P(
      "M0.125 0.1667L0.4637 0.1667C0.4845 0.1667 0.5021 0.182 0.505 0.2026L0.5417 0.4686",
    ),
    o,
  ),
  g.path(P("M0.1667 0.4583L0.1667 0.1667"), o),
  g.path(P("M0.2917 0.625L0.2921 0.625"), o),
  g.path(P("M0.3333 0.4208L0.3333 0.1667"), o),
  g.circle(X(0.75), Y(0.75), S(0.1667), o),
  g.circle(X(0.2917), Y(0.625), S(0.4167), o),
];
