// Lucide "train-front-tunnel" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTrainFrontTunnel: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.0833 0.9167L0.0833 0.5C0.0833 0.2699 0.2699 0.0833 0.5 0.0833 0.7301 0.0833 0.9167 0.2699 0.9167 0.5L0.9167 0.9167",
    ),
    o,
  ),
  g.path(
    P(
      "M0.625 0.2833L0.625 0.3417C0.625 0.4061 0.569 0.4583 0.5 0.4583 0.431 0.4583 0.375 0.4061 0.375 0.3417L0.375 0.2833",
    ),
    o,
  ),
  g.path(P("M0.4167 0.625L0.4171 0.625"), o),
  g.path(P("M0.5833 0.625L0.5837 0.625"), o),
  g.path(
    P(
      "M0.4167 0.7917C0.3246 0.7917 0.25 0.717 0.25 0.625L0.25 0.5C0.25 0.3619 0.3619 0.25 0.5 0.25 0.6381 0.25 0.75 0.3619 0.75 0.5L0.75 0.625C0.75 0.717 0.6754 0.7917 0.5833 0.7917Z",
    ),
    o,
  ),
  g.path(P("M0.375 0.7917L0.2917 0.9167"), o),
  g.path(P("M0.625 0.7917L0.7083 0.9167"), o),
];
