// Lucide "train-track" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTrainTrack: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.0833 0.7083L0.7083 0.0833"), o),
  g.path(P("M0.0833 0.5833L0.4167 0.9167"), o),
  g.path(P("M0.2083 0.4583L0.5417 0.7917"), o),
  g.path(P("M0.3333 0.3333L0.6667 0.6667"), o),
  g.path(P("M0.4583 0.2083L0.7917 0.5417"), o),
  g.path(P("M0.5833 0.0833L0.9167 0.4167"), o),
  g.path(P("M0.2917 0.9167L0.9167 0.2917"), o),
];
