// Lucide "building" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideBuilding: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.4167L0.5004 0.4167"), o),
  g.path(P("M0.5 0.5833L0.5004 0.5833"), o),
  g.path(P("M0.5 0.25L0.5004 0.25"), o),
  g.path(P("M0.6667 0.4167L0.6671 0.4167"), o),
  g.path(P("M0.6667 0.5833L0.6671 0.5833"), o),
  g.path(P("M0.6667 0.25L0.6671 0.25"), o),
  g.path(P("M0.3333 0.4167L0.3337 0.4167"), o),
  g.path(P("M0.3333 0.5833L0.3337 0.5833"), o),
  g.path(P("M0.3333 0.25L0.3337 0.25"), o),
  g.path(
    P(
      "M0.375 0.9167L0.375 0.7917C0.375 0.7687 0.3937 0.75 0.4167 0.75L0.5833 0.75C0.6063 0.75 0.625 0.7687 0.625 0.7917L0.625 0.9167",
    ),
    o,
  ),
  g.path(
    P(
      "M0.25 0.0833L0.75 0.0833Q0.8333 0.0833 0.8333 0.1667L0.8333 0.8333Q0.8333 0.9167 0.75 0.9167L0.25 0.9167Q0.1667 0.9167 0.1667 0.8333L0.1667 0.1667Q0.1667 0.0833 0.25 0.0833Z",
    ),
    o,
  ),
];
