// Lucide "circle-user-round" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCircleUserRound: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(
    P(
      "M0.7469 0.8357C0.7276 0.7143 0.6229 0.625 0.5 0.625 0.3771 0.625 0.2724 0.7143 0.2531 0.8357",
    ),
    o,
  ),
  g.circle(X(0.5), Y(0.4583), S(0.3333), o),
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
];
