// Lucide "cog" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCog: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.4583 0.4279L0.2917 0.1392"), o),
  g.path(P("M0.4583 0.5721L0.2917 0.8608"), o),
  g.path(P("M0.5 0.9167L0.5 0.8333"), o),
  g.path(P("M0.5 0.0833L0.5 0.1667"), o),
  g.path(P("M0.5833 0.5L0.9167 0.5"), o),
  g.path(P("M0.7083 0.8608L0.6667 0.7887"), o),
  g.path(P("M0.7083 0.1392L0.6667 0.2112"), o),
  g.path(P("M0.0833 0.5L0.1667 0.5"), o),
  g.path(P("M0.8608 0.7083L0.7887 0.6667"), o),
  g.path(P("M0.8608 0.2917L0.7887 0.3333"), o),
  g.path(P("M0.1392 0.7083L0.2112 0.6667"), o),
  g.path(P("M0.1392 0.2917L0.2112 0.3333"), o),
  g.circle(X(0.5), Y(0.5), S(0.1667), o),
  g.circle(X(0.5), Y(0.5), S(0.6667), o),
];
