// Lucide "settings-2" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSettings2: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.5833 0.7083L0.2083 0.7083"), o),
  g.path(P("M0.7917 0.2917L0.4167 0.2917"), o),
  g.circle(X(0.7083), Y(0.7083), S(0.25), o),
  g.circle(X(0.2917), Y(0.2917), S(0.25), o),
];
