// Lucide "share" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideShare: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.0833L0.5 0.625"), o),
  g.path(P("M0.6667 0.25L0.5 0.0833 0.3333 0.25"), o),
  g.path(
    P(
      "M0.1667 0.5L0.1667 0.8333C0.1667 0.8794 0.204 0.9167 0.25 0.9167L0.75 0.9167C0.796 0.9167 0.8333 0.8794 0.8333 0.8333L0.8333 0.5",
    ),
    o,
  ),
];
