// Lucide "shield-cog-corner" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideShieldCogCorner: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(
    P(
      "M0.4583 0.9167C0.2997 0.8562 0.1667 0.7514 0.1667 0.5417L0.1667 0.25C0.1667 0.227 0.1853 0.2083 0.2083 0.2083 0.2917 0.2083 0.3958 0.1583 0.4683 0.095 0.4866 0.0794 0.5134 0.0794 0.5317 0.095 0.6046 0.1588 0.7083 0.2083 0.7917 0.2083 0.8147 0.2083 0.8333 0.227 0.8333 0.25L0.8333 0.4167",
    ),
    o,
  ),
  g.path(P("M0.6218 0.6895L0.5833 0.6735"), o),
  g.path(P("M0.6218 0.7851L0.5833 0.8011"), o),
  g.path(P("M0.6895 0.6218L0.6735 0.5833"), o),
  g.path(P("M0.6895 0.8528L0.6735 0.8913"), o),
  g.path(P("M0.7851 0.6218L0.8011 0.5833"), o),
  g.path(P("M0.801 0.8913L0.7851 0.8528"), o),
  g.path(P("M0.8528 0.6895L0.8912 0.6735"), o),
  g.path(P("M0.8528 0.7851L0.8912 0.8011"), o),
  g.circle(X(0.7373), Y(0.7373), S(0.25), o),
];
