// Lucide "user-search" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideUserSearch: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.4167), Y(0.2917), S(0.3333), o),
  g.path(
    P(
      "M0.4292 0.625L0.2917 0.625C0.1996 0.625 0.125 0.6996 0.125 0.7917L0.125 0.875",
    ),
    o,
  ),
  g.circle(X(0.7083), Y(0.7083), S(0.25), o),
  g.path(P("M0.875 0.875L0.7958 0.7958"), o),
];
