// Lucide "user" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideUser: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(
    P(
      "M0.7917 0.875L0.7917 0.7917C0.7917 0.6996 0.717 0.625 0.625 0.625L0.375 0.625C0.283 0.625 0.2083 0.6996 0.2083 0.7917L0.2083 0.875",
    ),
    o,
  ),
  g.circle(X(0.5), Y(0.2917), S(0.3333), o),
];
