// Lucide "user-round-minus" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideUserRoundMinus: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(
    P(
      "M0.0833 0.875C0.0833 0.744 0.1601 0.6251 0.2795 0.5712 0.399 0.5173 0.5389 0.5383 0.6372 0.625",
    ),
    o,
  ),
  g.circle(X(0.4167), Y(0.3333), S(0.4167), o),
  g.path(P("M0.9167 0.7917L0.6667 0.7917"), o),
];
