// Lucide "user-minus" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideUserMinus: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(
    P(
      "M0.6667 0.875L0.6667 0.7917C0.6667 0.6996 0.592 0.625 0.5 0.625L0.25 0.625C0.158 0.625 0.0833 0.6996 0.0833 0.7917L0.0833 0.875",
    ),
    o,
  ),
  g.circle(X(0.375), Y(0.2917), S(0.3333), o),
  g.line(X(0.9167), Y(0.4583), X(0.6667), Y(0.4583), o),
];
