// Lucide "user-round-x" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideUserRoundX: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.6875 0.6875L0.8958 0.8958"), o),
  g.path(
    P(
      "M0.0833 0.875C0.0833 0.7599 0.1427 0.6528 0.2405 0.592 0.3382 0.5311 0.4605 0.525 0.5638 0.5758",
    ),
    o,
  ),
  g.path(P("M0.8958 0.6875L0.6875 0.8958"), o),
  g.circle(X(0.4167), Y(0.3333), S(0.4167), o),
];
