// Lucide "user-round" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideUserRound: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.3333), S(0.4167), o),
  g.path(
    P(
      "M0.8333 0.875C0.8333 0.6909 0.6841 0.5417 0.5 0.5417 0.3159 0.5417 0.1667 0.6909 0.1667 0.875",
    ),
    o,
  ),
];
