// Lucide "user-round-search" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideUserRoundSearch: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.4167), Y(0.3333), S(0.4167), o),
  g.path(
    P(
      "M0.0833 0.875C0.0833 0.7686 0.1341 0.6686 0.2201 0.6058 0.306 0.5431 0.4167 0.5251 0.5181 0.5575",
    ),
    o,
  ),
  g.circle(X(0.75), Y(0.75), S(0.25), o),
  g.path(P("M0.9167 0.9167L0.8375 0.8375"), o),
];
