// Lucide "bluetooth-off" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideBluetoothOff: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.7083 0.7083L0.5 0.9167 0.5 0.5 0.2917 0.7083"), o),
  g.path(P("M0.0833 0.0833L0.9167 0.9167"), o),
  g.path(P("M0.6042 0.3958L0.7083 0.2917 0.5 0.0833 0.5 0.2708"), o),
];
