// Lucide "bluetooth" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideBluetooth: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.2917 0.2917L0.7083 0.7083 0.5 0.9167 0.5 0.0833 0.7083 0.2917 0.2917 0.7083",
    ),
    o,
  ),
];
