// Lucide "circle-power" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCirclePower: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
  g.path(P("M0.5 0.2917L0.5 0.4583"), o),
  g.path(
    P(
      "M0.3332 0.3751C0.2688 0.4611 0.2804 0.582 0.3599 0.6542 0.4394 0.7265 0.5608 0.7264 0.6403 0.654 0.7197 0.5817 0.7311 0.4608 0.6666 0.3749",
    ),
    o,
  ),
];
