// Lucide "power" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucidePower: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.0833L0.5 0.5"), o),
  g.path(
    P(
      "M0.7667 0.275C0.9129 0.4212 0.9131 0.6582 0.7672 0.8047 0.6212 0.9513 0.3842 0.952 0.2374 0.8064 0.0906 0.6608 0.0893 0.4238 0.2346 0.2767",
    ),
    o,
  ),
];
