// Lucide "signal-zero" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSignalZero: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.0833 0.8333L0.0837 0.8333"), o),
];
