// Lucide "signal" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSignal: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.0833 0.8333L0.0837 0.8333"), o),
  g.path(P("M0.2917 0.8333L0.2917 0.6667"), o),
  g.path(P("M0.5 0.8333L0.5 0.5"), o),
  g.path(P("M0.7083 0.8333L0.7083 0.3333"), o),
  g.path(P("M0.9167 0.1667L0.9167 0.8333"), o),
];
