// Lucide "smartphone" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSmartphone: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.2917 0.0833L0.7083 0.0833Q0.7917 0.0833 0.7917 0.1667L0.7917 0.8333Q0.7917 0.9167 0.7083 0.9167L0.2917 0.9167Q0.2083 0.9167 0.2083 0.8333L0.2083 0.1667Q0.2083 0.0833 0.2917 0.0833Z",
    ),
    o,
  ),
  g.path(P("M0.5 0.75L0.5004 0.75"), o),
];
