// Lucide "wifi-zero" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideWifiZero: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.8333L0.5004 0.8333"), o),
];
