// Lucide "wifi" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideWifi: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.8333L0.5004 0.8333"), o),
  g.path(P("M0.0833 0.3675C0.3206 0.1553 0.6794 0.1553 0.9167 0.3675"), o),
  g.path(P("M0.2083 0.5358C0.3704 0.377 0.6296 0.377 0.7917 0.5358"), o),
  g.path(P("M0.3542 0.6845C0.4352 0.6051 0.5648 0.6051 0.6458 0.6845"), o),
];
