// Lucide "wifi-cog" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideWifiCog: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.596 0.8137L0.6345 0.7978"), o),
  g.path(P("M0.6345 0.7022L0.596 0.6862"), o),
  g.path(P("M0.7022 0.6345L0.6862 0.596"), o),
  g.path(P("M0.7022 0.8655L0.6862 0.904"), o),
  g.path(P("M0.7978 0.6345L0.8138 0.596"), o),
  g.path(P("M0.8137 0.904L0.7978 0.8655"), o),
  g.path(P("M0.0833 0.3258C0.3206 0.1136 0.6794 0.1136 0.9167 0.3258"), o),
  g.path(P("M0.8655 0.7022L0.904 0.6862"), o),
  g.path(P("M0.8655 0.7978L0.904 0.8138"), o),
  g.path(P("M0.2083 0.4941C0.3357 0.3693 0.5283 0.3394 0.6875 0.4197"), o),
  g.path(P("M0.3542 0.6429C0.3819 0.6157 0.4168 0.5967 0.4547 0.5883"), o),
  g.circle(X(0.75), Y(0.75), S(0.25), o),
];
