// Lucide "chevrons-left-right-ellipsis" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideChevronsLeftRightEllipsis: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.5L0.5004 0.5"), o),
  g.path(P("M0.6667 0.5L0.6671 0.5"), o),
  g.path(P("M0.7083 0.2917L0.9167 0.5 0.7083 0.7083"), o),
  g.path(P("M0.2917 0.2917L0.0833 0.5 0.2917 0.7083"), o),
  g.path(P("M0.3333 0.5L0.3337 0.5"), o),
];
