// Lucide "circle-stop" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCircleStop: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
  g.path(
    P(
      "M0.4167 0.375L0.5833 0.375Q0.625 0.375 0.625 0.4167L0.625 0.5833Q0.625 0.625 0.5833 0.625L0.4167 0.625Q0.375 0.625 0.375 0.5833L0.375 0.4167Q0.375 0.375 0.4167 0.375Z",
    ),
    o,
  ),
];
