// Lucide "list-x" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideListX: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.6667 0.2083L0.125 0.2083"), o),
  g.path(P("M0.4583 0.5L0.125 0.5"), o),
  g.path(P("M0.6667 0.7917L0.125 0.7917"), o),
  g.path(P("M0.6458 0.3958L0.8542 0.6042"), o),
  g.path(P("M0.8542 0.3958L0.6458 0.6042"), o),
];
