// Lucide "list-music" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideListMusic: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.6667 0.2083L0.125 0.2083"), o),
  g.path(P("M0.4583 0.5L0.125 0.5"), o),
  g.path(P("M0.4583 0.7917L0.125 0.7917"), o),
  g.path(P("M0.875 0.6667L0.875 0.2083"), o),
  g.circle(X(0.75), Y(0.6667), S(0.25), o),
];
