// Lucide "music-2" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMusic2: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.3333), Y(0.75), S(0.3333), o),
  g.path(P("M0.5 0.75L0.5 0.0833 0.7917 0.25"), o),
];
