// Lucide "music-4" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMusic4: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.375 0.75L0.375 0.2083 0.875 0.125 0.875 0.6667"), o),
  g.path(P("M0.375 0.375L0.875 0.2917"), o),
  g.circle(X(0.25), Y(0.75), S(0.25), o),
  g.circle(X(0.75), Y(0.6667), S(0.25), o),
];
