// Lucide "presentation" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucidePresentation: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.0833 0.125L0.9167 0.125"), o),
  g.path(
    P(
      "M0.875 0.125L0.875 0.5833C0.875 0.6294 0.8377 0.6667 0.7917 0.6667L0.2083 0.6667C0.1623 0.6667 0.125 0.6294 0.125 0.5833L0.125 0.125",
    ),
    o,
  ),
  g.path(P("M0.2917 0.875L0.5 0.6667 0.7083 0.875"), o),
];
