// Lucide "birdhouse" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideBirdhouse: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.5 0.75L0.5 0.9167"), o),
  g.path(P("M0.7083 0.75L0.7898 0.2722"), o),
  g.path(
    P(
      "M0.125 0.3333L0.4508 0.0994C0.4801 0.078 0.5199 0.078 0.5492 0.0994L0.875 0.3333",
    ),
    o,
  ),
  g.path(P("M0.1667 0.75L0.8333 0.75"), o),
  g.path(P("M0.2917 0.75L0.2102 0.2722"), o),
  g.circle(X(0.5), Y(0.4167), S(0.1667), o),
];
