import { browser } from "./devices/browser";
import { robot } from "./devices/robot";
import { chip } from "./hardware/chip";
import { cube } from "./hardware/cube";
import { disk } from "./hardware/disk";
import { memory } from "./hardware/memory";
import { chart } from "./data/chart";
import { queue } from "./data/queue";
import { warning } from "./security/warning";
import { chat } from "./people/chat";
import { gear } from "./development/gear";
import { cart } from "./everyday/cart";
import { home } from "./everyday/home";
import { lightning } from "./everyday/lightning";
import { money } from "./everyday/money";
import { question } from "./marks/question";
import { LUCIDE } from "./lucide";
import type { IconDrawing } from "./types";

// Every icon a scene file can use, by name ("type": "icon", "name": ...):
// all Lucide icons (lucide/, generated by icon-tools; see lucide.dev/icons
// for names) plus our own hand-made ones below for things Lucide lacks.
// Where both have a name, Lucide's drawing is used.
//
// To add a hand-made icon: create <name>.ts in the folder for its group
// (see types.ts for the helpers) and add it here, under the same group.
// The scene file schema takes its list of names from ICONS, so nothing
// else needs to change.
const HAND_MADE = {
  // devices
  browser,
  robot,
  // hardware
  chip,
  memory,
  disk,
  cube,
  // files and data
  chart,
  queue,
  // security
  warning,
  // people and communication
  chat,
  // development
  gear,
  // everyday
  home,
  cart,
  money,
  lightning,
  // marks
  question,
} satisfies Record<string, IconDrawing>;

export const ICONS = { ...HAND_MADE, ...LUCIDE };

export type IconName = keyof typeof ICONS;

export const ICON_NAMES = Object.keys(ICONS) as [IconName, ...IconName[]];
