// Lucide "egg" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideEgg: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.5 0.0833C0.3333 0.0833 0.1667 0.3333 0.1667 0.5833 0.1667 0.7674 0.3159 0.9167 0.5 0.9167 0.6841 0.9167 0.8333 0.7674 0.8333 0.5833 0.8333 0.3333 0.6667 0.0833 0.5 0.0833",
    ),
    o,
  ),
];
