// Lucide "fish-symbol" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideFishSymbol: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.0833 0.6667C0.0833 0.6667 0.4583 0.0417 0.9167 0.5 0.4583 0.9583 0.0833 0.3333 0.0833 0.3333",
    ),
    o,
  ),
];
