// Lucide "compass" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCompass: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
  g.path(
    P(
      "M0.6767 0.3233L0.6015 0.5488C0.5932 0.5737 0.5737 0.5932 0.5488 0.6015L0.3233 0.6767 0.3985 0.4512C0.4068 0.4263 0.4263 0.4068 0.4512 0.3985Z",
    ),
    o,
  ),
];
