// Lucide "globe" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideGlobe: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
  g.path(
    P(
      "M0.5 0.0833C0.2778 0.3167 0.2778 0.6833 0.5 0.9167 0.7222 0.6833 0.7222 0.3167 0.5 0.0833",
    ),
    o,
  ),
  g.path(P("M0.0833 0.5L0.9167 0.5"), o),
];
