// Lucide "locate-fixed" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideLocateFixed: IconDrawing = ({ g, o, X, Y, S }) => [
  g.line(X(0.0833), Y(0.5), X(0.2083), Y(0.5), o),
  g.line(X(0.7917), Y(0.5), X(0.9167), Y(0.5), o),
  g.line(X(0.5), Y(0.0833), X(0.5), Y(0.2083), o),
  g.line(X(0.5), Y(0.7917), X(0.5), Y(0.9167), o),
  g.circle(X(0.5), Y(0.5), S(0.5833), o),
  g.circle(X(0.5), Y(0.5), S(0.25), o),
];
