// Lucide "navigation-2-off" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideNavigation2Off: IconDrawing = ({ g, o, X, Y, P }) => [
  g.path(
    P("M0.3879 0.3879L0.2083 0.875 0.5 0.7083 0.7917 0.875 0.7429 0.7429"),
    o,
  ),
  g.path(P("M0.6054 0.37L0.5 0.0833 0.4512 0.2154"), o),
  g.line(X(0.0833), Y(0.0833), X(0.9167), Y(0.9167), o),
];
