// Lucide "navigation-2" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideNavigation2: IconDrawing = ({ g, o, X, Y }) => [
  g.polygon(
    [
      [X(0.5), Y(0.0833)],
      [X(0.7917), Y(0.875)],
      [X(0.5), Y(0.7083)],
      [X(0.2083), Y(0.875)],
      [X(0.5), Y(0.0833)],
    ],
    o,
  ),
];
