// Lucide "navigation" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideNavigation: IconDrawing = ({ g, o, X, Y }) => [
  g.polygon(
    [
      [X(0.125), Y(0.4583)],
      [X(0.9167), Y(0.0833)],
      [X(0.5417), Y(0.875)],
      [X(0.4583), Y(0.5417)],
      [X(0.125), Y(0.4583)],
    ],
    o,
  ),
];
