// Lucide "tent" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTent: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.1458 0.875L0.5833 0.125"), o),
  g.path(P("M0.8542 0.875L0.4167 0.125"), o),
  g.path(P("M0.6458 0.875L0.5 0.625 0.3542 0.875"), o),
  g.path(P("M0.0833 0.875L0.9167 0.875"), o),
];
