// Lucide "forward" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideForward: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.625 0.7083L0.8333 0.5 0.625 0.2917"), o),
  g.path(
    P(
      "M0.1667 0.75L0.1667 0.6667C0.1667 0.5746 0.2413 0.5 0.3333 0.5L0.8333 0.5",
    ),
    o,
  ),
];
