// Lucide "mailbox" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMailbox: IconDrawing = ({ g, o, X, Y, P }) => [
  g.path(
    P(
      "M0.9167 0.7083C0.9167 0.7544 0.8794 0.7917 0.8333 0.7917L0.1667 0.7917C0.1206 0.7917 0.0833 0.7544 0.0833 0.7083L0.0833 0.3958C0.0833 0.2917 0.1667 0.2083 0.2708 0.2083L0.75 0.2083C0.8417 0.2083 0.9167 0.2833 0.9167 0.375L0.9167 0.7083Z",
    ),
    o,
  ),
  g.linearPath(
    [
      [X(0.625), Y(0.375)],
      [X(0.75), Y(0.375)],
      [X(0.75), Y(0.4583)],
    ],
    o,
  ),
  g.path(
    P(
      "M0.2708 0.2083C0.375 0.2083 0.4583 0.2917 0.4583 0.3958L0.4583 0.7083C0.4583 0.7544 0.421 0.7917 0.375 0.7917",
    ),
    o,
  ),
  g.line(X(0.25), Y(0.4167), X(0.2917), Y(0.4167), o),
];
