// Lucide "mail-search" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMailSearch: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(
    P(
      "M0.9167 0.5208L0.9167 0.25C0.9167 0.204 0.8794 0.1667 0.8333 0.1667L0.1667 0.1667C0.1206 0.1667 0.0833 0.204 0.0833 0.25L0.0833 0.75C0.0833 0.7958 0.1208 0.8333 0.1667 0.8333L0.4792 0.8333",
    ),
    o,
  ),
  g.path(
    P(
      "M0.9167 0.2917L0.5429 0.5292C0.5167 0.5456 0.4833 0.5456 0.4571 0.5292L0.0833 0.2917",
    ),
    o,
  ),
  g.path(
    P(
      "M0.75 0.875C0.819 0.875 0.875 0.819 0.875 0.75 0.875 0.681 0.819 0.625 0.75 0.625 0.681 0.625 0.625 0.681 0.625 0.75 0.625 0.819 0.681 0.875 0.75 0.875Z",
    ),
    o,
  ),
  g.circle(X(0.75), Y(0.75), S(0.25), o),
  g.path(P("M0.9167 0.9167L0.8542 0.8542"), o),
];
