// Lucide "reply-all" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideReplyAll: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.7083L0.2917 0.5 0.5 0.2917"), o),
  g.path(
    P("M0.9167 0.75L0.9167 0.6667C0.9167 0.5746 0.842 0.5 0.75 0.5L0.2917 0.5"),
    o,
  ),
  g.path(P("M0.2917 0.7083L0.0833 0.5 0.2917 0.2917"), o),
];
