// Lucide "reply" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideReply: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.8333 0.75L0.8333 0.6667C0.8333 0.5746 0.7587 0.5 0.6667 0.5L0.1667 0.5",
    ),
    o,
  ),
  g.path(P("M0.375 0.7083L0.1667 0.5 0.375 0.2917"), o),
];
