// Lucide "barcode" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideBarcode: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.125 0.2083L0.125 0.7917"), o),
  g.path(P("M0.3333 0.2083L0.3333 0.7917"), o),
  g.path(P("M0.5 0.2083L0.5 0.7917"), o),
  g.path(P("M0.7083 0.2083L0.7083 0.7917"), o),
  g.path(P("M0.875 0.2083L0.875 0.7917"), o),
];
