// Lucide "zodiac-sagittarius" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideZodiacSagittarius: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.625 0.125L0.875 0.125 0.875 0.375"), o),
  g.path(P("M0.875 0.125L0.125 0.875"), o),
  g.path(P("M0.375 0.375L0.625 0.625"), o),
];
