// Lucide "zodiac-taurus" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideZodiacTaurus: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.625), S(0.5), o),
  g.path(
    P(
      "M0.75 0.125C0.75 0.2631 0.6381 0.375 0.5 0.375 0.3619 0.375 0.25 0.2631 0.25 0.125",
    ),
    o,
  ),
];
