// Lucide "zodiac-gemini" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideZodiacGemini: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.6667 0.1885L0.6667 0.8114"), o),
  g.path(P("M0.8333 0.125C0.625 0.2361 0.375 0.2361 0.1667 0.125"), o),
  g.path(P("M0.1667 0.875C0.375 0.7639 0.625 0.7639 0.8333 0.875"), o),
  g.path(P("M0.3333 0.1885L0.3333 0.8114"), o),
];
