// Lucide "blinds" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideBlinds: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.125 0.125L0.875 0.125"), o),
  g.path(P("M0.8333 0.2917L0.3333 0.2917"), o),
  g.path(P("M0.8333 0.4583L0.3333 0.4583"), o),
  g.path(P("M0.4167 0.7917L0.8333 0.7917"), o),
  g.path(P("M0.3333 0.625L0.8333 0.625"), o),
  g.path(P("M0.1667 0.125L0.1667 0.7083"), o),
  g.circle(X(0.1667), Y(0.7917), S(0.1667), o),
];
