// Lucide "heater" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideHeater: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.4583 0.3333C0.5417 0.2083 0.375 0.2083 0.4583 0.0833"), o),
  g.path(P("M0.6458 0.3333C0.7292 0.2083 0.5625 0.2083 0.6458 0.0833"), o),
  g.path(P("M0.25 0.4167L0.2504 0.4167"), o),
  g.path(P("M0.25 0.5833L0.2504 0.5833"), o),
  g.path(P("M0.4167 0.6667L0.4167 0.5"), o),
  g.path(P("M0.5833 0.6667L0.5833 0.5"), o),
  g.path(P("M0.75 0.6667L0.75 0.5"), o),
  g.path(
    P(
      "M0.8333 0.25C0.8794 0.25 0.9167 0.2873 0.9167 0.3333L0.9167 0.75C0.9167 0.796 0.8794 0.8333 0.8333 0.8333L0.1667 0.8333C0.1206 0.8333 0.0833 0.796 0.0833 0.75L0.0833 0.3333C0.0833 0.2873 0.1206 0.25 0.1667 0.25L0.2917 0.25",
    ),
    o,
  ),
  g.path(P("M0.2083 0.8333L0.2083 0.9167"), o),
  g.path(P("M0.7917 0.8333L0.7917 0.9167"), o),
];
