// Lucide "rocking-chair" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideRockingChair: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.625 0.5417L0.7795 0.8507"), o),
  g.path(P("M0.125 0.7917C0.3472 0.9583 0.6528 0.9583 0.875 0.7917"), o),
  g.path(
    P(
      "M0.125 0.0833L0.2587 0.4847C0.2701 0.5188 0.302 0.5417 0.3379 0.5417L0.75 0.5417",
    ),
    o,
  ),
  g.path(P("M0.375 0.5417L0.2205 0.8507"), o),
];
