// Lucide "toothbrush-sparkles" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideToothbrushSparkles: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.4167 0.125L0.3333 0.125"), o),
  g.path(P("M0.6078 0.4756L0.9167 0.1667"), o),
  g.path(P("M0.625 0.4583C0.6192 0.4641 0.6133 0.4697 0.6071 0.475"), o),
  g.path(
    P(
      "M0.0833 0.9167L0.375 0.625C0.4524 0.5476 0.5297 0.5421 0.6071 0.475L0.5244 0.3922C0.5006 0.3684 0.4935 0.3326 0.5064 0.3014 0.5193 0.2703 0.5496 0.25 0.5833 0.25 0.5833 0.204 0.6206 0.1667 0.6667 0.1667 0.6667 0.1345 0.6852 0.1052 0.7142 0.0914 0.7432 0.0776 0.7776 0.0817 0.8026 0.102L0.8922 0.1911",
    ),
    o,
  ),
  g.path(P("M0.8333 0.625L0.8333 0.7917"), o),
  g.path(P("M0.9167 0.7083L0.75 0.7083"), o),
  g.path(P("M0.1667 0.2083L0.1667 0.375"), o),
  g.path(P("M0.25 0.2917L0.0833 0.2917"), o),
  g.path(P("M0.375 0.0833L0.375 0.1667"), o),
];
