// Lucide "check-line" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCheckLine: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.8333 0.1667L0.375 0.625"), o),
  g.path(P("M0.875 0.7917L0.125 0.7917"), o),
  g.path(P("M0.375 0.625L0.1667 0.4167"), o),
];
