// Lucide "check-check" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCheckCheck: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.75 0.25L0.2917 0.7083 0.0833 0.5"), o),
  g.path(P("M0.9167 0.4167L0.6042 0.7292 0.5417 0.6667"), o),
];
