// Lucide "square-check-big" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSquareCheckBig: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.875 0.444L0.875 0.7917C0.875 0.8377 0.8377 0.875 0.7917 0.875L0.2083 0.875C0.1623 0.875 0.125 0.8377 0.125 0.7917L0.125 0.2083C0.125 0.1623 0.1623 0.125 0.2083 0.125L0.7227 0.125",
    ),
    o,
  ),
  g.path(P("M0.375 0.4583L0.5 0.5833 0.9167 0.1667"), o),
];
