// Lucide "x" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideX: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.75 0.25L0.25 0.75"), o),
  g.path(P("M0.25 0.25L0.75 0.75"), o),
];
