// Lucide "angle" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideAngle: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.125 0.125L0.125 0.7917C0.125 0.8377 0.1623 0.875 0.2083 0.875L0.875 0.875",
    ),
    o,
  ),
  g.path(P("M0.125 0.4583C0.3551 0.4583 0.5417 0.6449 0.5417 0.875"), o),
];
