// Lucide "circle-minus" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCircleMinus: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
  g.path(P("M0.3333 0.5L0.6667 0.5"), o),
];
