// Lucide "circle-divide" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCircleDivide: IconDrawing = ({ g, o, X, Y, S }) => [
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
  g.line(X(0.3333), Y(0.5), X(0.6667), Y(0.5), o),
  g.line(X(0.5), Y(0.6667), X(0.5), Y(0.6667), o),
  g.line(X(0.5), Y(0.3333), X(0.5), Y(0.3333), o),
];
