// Lucide "equal" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideEqual: IconDrawing = ({ g, o, X, Y }) => [
  g.line(X(0.2083), Y(0.375), X(0.7917), Y(0.375), o),
  g.line(X(0.2083), Y(0.625), X(0.7917), Y(0.625), o),
];
