// Lucide "tally-1" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTally1: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.1667 0.1667L0.1667 0.8333"), o),
];
