// Lucide "tally-3" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTally3: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.1667 0.1667L0.1667 0.8333"), o),
  g.path(P("M0.375 0.1667L0.375 0.8333"), o),
  g.path(P("M0.5833 0.1667L0.5833 0.8333"), o),
];
