// Lucide "hotel" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideHotel: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.4167 0.9167L0.4167 0.6429"), o),
  g.path(P("M0.5 0.4583L0.5004 0.4583"), o),
  g.path(P("M0.5 0.2917L0.5004 0.2917"), o),
  g.path(P("M0.5833 0.6429L0.5833 0.9167"), o),
  g.path(P("M0.625 0.6667C0.5509 0.6111 0.4491 0.6111 0.375 0.6667"), o),
  g.path(P("M0.6667 0.4583L0.6671 0.4583"), o),
  g.path(P("M0.6667 0.2917L0.6671 0.2917"), o),
  g.path(P("M0.3333 0.4583L0.3337 0.4583"), o),
  g.path(P("M0.3333 0.2917L0.3337 0.2917"), o),
  g.path(
    P(
      "M0.25 0.0833L0.75 0.0833Q0.8333 0.0833 0.8333 0.1667L0.8333 0.8333Q0.8333 0.9167 0.75 0.9167L0.25 0.9167Q0.1667 0.9167 0.1667 0.8333L0.1667 0.1667Q0.1667 0.0833 0.25 0.0833Z",
    ),
    o,
  ),
];
