// Lucide "house-cog" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideHouseCog: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(
    P(
      "M0.441 0.875L0.2083 0.875C0.1623 0.875 0.125 0.8377 0.125 0.7917L0.125 0.4167C0.125 0.3921 0.1358 0.3689 0.1545 0.353L0.4462 0.103C0.4773 0.0768 0.5227 0.0768 0.5538 0.103L0.8455 0.353C0.8642 0.3689 0.875 0.3922 0.875 0.4167L0.875 0.441",
    ),
    o,
  ),
  g.path(
    P(
      "M0.5833 0.5L0.4167 0.5C0.3937 0.5 0.375 0.5187 0.375 0.5417L0.375 0.875",
    ),
    o,
  ),
  g.path(P("M0.596 0.8137L0.6345 0.7978"), o),
  g.path(P("M0.6345 0.7022L0.596 0.6862"), o),
  g.path(P("M0.7022 0.6345L0.6862 0.596"), o),
  g.path(P("M0.7022 0.8655L0.6862 0.904"), o),
  g.path(P("M0.7978 0.6345L0.8138 0.596"), o),
  g.path(P("M0.8137 0.904L0.7978 0.8655"), o),
  g.path(P("M0.8655 0.7022L0.904 0.6862"), o),
  g.path(P("M0.8655 0.7978L0.904 0.8138"), o),
  g.circle(X(0.75), Y(0.75), S(0.25), o),
];
