// Lucide "lighthouse" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideLighthouse: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.125L0.5 0.0833"), o),
  g.path(
    P(
      "M0.6694 0.7027L0.2917 0.9167 0.375 0.4583 0.375 0.25C0.375 0.181 0.431 0.125 0.5 0.125 0.569 0.125 0.625 0.181 0.625 0.25L0.625 0.4583 0.7083 0.9167",
    ),
    o,
  ),
  g.path(P("M0.8247 0.1875L0.8608 0.1667"), o),
  g.path(P("M0.8249 0.5625L0.861 0.5833"), o),
  g.path(P("M0.875 0.375L0.9167 0.375"), o),
  g.path(P("M0.125 0.375L0.0833 0.375"), o),
  g.path(P("M0.1751 0.5625L0.139 0.5833"), o),
  g.path(P("M0.1753 0.1875L0.1392 0.1667"), o),
  g.path(P("M0.2292 0.9167L0.7708 0.9167"), o),
  g.path(P("M0.3305 0.7031L0.6379 0.529"), o),
  g.path(P("M0.3333 0.4583L0.6667 0.4583"), o),
  g.path(P("M0.3333 0.2917L0.6667 0.2917"), o),
];
