// Lucide "utility-pole" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideUtilityPole: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.0833L0.5 0.9167"), o),
  g.path(P("M0.0833 0.2083L0.9167 0.2083"), o),
  g.path(P("M0.125 0.125L0.125 0.2083"), o),
  g.path(P("M0.2917 0.125L0.2917 0.2083"), o),
  g.path(P("M0.7083 0.125L0.7083 0.2083"), o),
  g.path(P("M0.875 0.125L0.875 0.2083"), o),
  g.path(P("M0.7917 0.2083L0.5 0.5 0.2083 0.2083"), o),
];
