// Lucide "contrast" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideContrast: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
  g.path(
    P(
      "M0.5 0.75C0.6381 0.75 0.75 0.6381 0.75 0.5 0.75 0.3619 0.6381 0.25 0.5 0.25L0.5 0.75Z",
    ),
    o,
  ),
];
