// Lucide "crosshair" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCrosshair: IconDrawing = ({ g, o, X, Y, S }) => [
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
  g.line(X(0.9167), Y(0.5), X(0.75), Y(0.5), o),
  g.line(X(0.25), Y(0.5), X(0.0833), Y(0.5), o),
  g.line(X(0.5), Y(0.25), X(0.5), Y(0.0833), o),
  g.line(X(0.5), Y(0.9167), X(0.5), Y(0.75), o),
];
