// Lucide "circle-pile" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCirclePile: IconDrawing = ({ g, o, X, Y, S }) => [
  g.circle(X(0.5), Y(0.7917), S(0.1667), o),
  g.circle(X(0.5), Y(0.2083), S(0.1667), o),
  g.circle(X(0.6667), Y(0.5), S(0.1667), o),
  g.circle(X(0.8333), Y(0.7917), S(0.1667), o),
  g.circle(X(0.1667), Y(0.7917), S(0.1667), o),
  g.circle(X(0.3333), Y(0.5), S(0.1667), o),
];
