// Lucide "cone" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCone: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(
    P(
      "M0.8708 0.7729L0.5375 0.1071C0.5305 0.0927 0.516 0.0836 0.5 0.0836 0.484 0.0836 0.4695 0.0927 0.4625 0.1071L0.1292 0.7729",
    ),
    o,
  ),
  g.ellipse(X(0.5), Y(0.7917), S(0.75), S(0.25), o),
];
