// Lucide "ellipse" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideEllipse: IconDrawing = ({ g, o, X, Y, S }) => [
  g.ellipse(X(0.5), Y(0.5), S(0.8333), S(0.5), o),
];
