// Lucide "line-squiggle" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideLineSquiggle: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.2917 0.1458C0.5 0.0625 0.5833 0.25 0.4167 0.3125 0.0625 0.4167 0.0833 0.625 0.2083 0.6667 0.4167 0.75 0.5833 0.25 0.7917 0.375 1 0.5 0.8125 0.9375 0.625 0.875 0.4167 0.7708 0.6458 0.4167 0.875 0.7917",
    ),
    o,
  ),
];
