// Lucide "rectangle-horizontal" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideRectangleHorizontal: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.1667 0.25L0.8333 0.25Q0.9167 0.25 0.9167 0.3333L0.9167 0.6667Q0.9167 0.75 0.8333 0.75L0.1667 0.75Q0.0833 0.75 0.0833 0.6667L0.0833 0.3333Q0.0833 0.25 0.1667 0.25Z",
    ),
    o,
  ),
];
