// Lucide "rectangle-vertical" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideRectangleVertical: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.3333 0.0833L0.6667 0.0833Q0.75 0.0833 0.75 0.1667L0.75 0.8333Q0.75 0.9167 0.6667 0.9167L0.3333 0.9167Q0.25 0.9167 0.25 0.8333L0.25 0.1667Q0.25 0.0833 0.3333 0.0833Z",
    ),
    o,
  ),
];
