// Lucide "squircle" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSquircle: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.5 0.125C0.8 0.125 0.875 0.2 0.875 0.5 0.875 0.8 0.8 0.875 0.5 0.875 0.2 0.875 0.125 0.8 0.125 0.5 0.125 0.2 0.2 0.125 0.5 0.125",
    ),
    o,
  ),
];
