// Lucide "torus" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTorus: IconDrawing = ({ g, o, X, Y, S }) => [
  g.ellipse(X(0.5), Y(0.4583), S(0.25), S(0.1667), o),
  g.ellipse(X(0.5), Y(0.5208), S(0.8333), S(0.7083), o),
];
