// Lucide "triangle-right" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTriangleRight: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.9167 0.75C0.9167 0.796 0.8794 0.8333 0.8333 0.8333L0.125 0.8333C0.0792 0.8333 0.0708 0.8083 0.1083 0.7792L0.85 0.1792C0.8875 0.15 0.9167 0.1625 0.9167 0.2083Z",
    ),
    o,
  ),
];
