// Lucide "grip-horizontal" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideGripHorizontal: IconDrawing = ({ g, o, X, Y, S }) => [
  g.circle(X(0.5), Y(0.375), S(0.0833), o),
  g.circle(X(0.7917), Y(0.375), S(0.0833), o),
  g.circle(X(0.2083), Y(0.375), S(0.0833), o),
  g.circle(X(0.5), Y(0.625), S(0.0833), o),
  g.circle(X(0.7917), Y(0.625), S(0.0833), o),
  g.circle(X(0.2083), Y(0.625), S(0.0833), o),
];
