// Lucide "grip-vertical" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideGripVertical: IconDrawing = ({ g, o, X, Y, S }) => [
  g.circle(X(0.375), Y(0.5), S(0.0833), o),
  g.circle(X(0.375), Y(0.2083), S(0.0833), o),
  g.circle(X(0.375), Y(0.7917), S(0.0833), o),
  g.circle(X(0.625), Y(0.5), S(0.0833), o),
  g.circle(X(0.625), Y(0.2083), S(0.0833), o),
  g.circle(X(0.625), Y(0.7917), S(0.0833), o),
];
