// Lucide "toggle-left" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideToggleLeft: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.375), Y(0.5), S(0.25), o),
  g.path(
    P(
      "M0.375 0.2083L0.625 0.2083Q0.9167 0.2083 0.9167 0.5L0.9167 0.5Q0.9167 0.7917 0.625 0.7917L0.375 0.7917Q0.0833 0.7917 0.0833 0.5L0.0833 0.5Q0.0833 0.2083 0.375 0.2083Z",
    ),
    o,
  ),
];
