// Lucide "arrow-down-wide-narrow" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideArrowDownWideNarrow: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.125 0.6667L0.2917 0.8333 0.4583 0.6667"), o),
  g.path(P("M0.2917 0.8333L0.2917 0.1667"), o),
  g.path(P("M0.4583 0.1667L0.875 0.1667"), o),
  g.path(P("M0.4583 0.3333L0.75 0.3333"), o),
  g.path(P("M0.4583 0.5L0.625 0.5"), o),
];
