// Lucide "asterisk" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideAsterisk: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.2083L0.5 0.7917"), o),
  g.path(P("M0.7527 0.354L0.2475 0.6457"), o),
  g.path(P("M0.2475 0.3543L0.7527 0.646"), o),
];
