// Lucide "binary" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideBinary: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.6667 0.5833L0.6667 0.5833Q0.75 0.5833 0.75 0.6667L0.75 0.75Q0.75 0.8333 0.6667 0.8333L0.6667 0.8333Q0.5833 0.8333 0.5833 0.75L0.5833 0.6667Q0.5833 0.5833 0.6667 0.5833Z",
    ),
    o,
  ),
  g.path(
    P(
      "M0.3333 0.1667L0.3333 0.1667Q0.4167 0.1667 0.4167 0.25L0.4167 0.3333Q0.4167 0.4167 0.3333 0.4167L0.3333 0.4167Q0.25 0.4167 0.25 0.3333L0.25 0.25Q0.25 0.1667 0.3333 0.1667Z",
    ),
    o,
  ),
  g.path(P("M0.25 0.8333L0.4167 0.8333"), o),
  g.path(P("M0.5833 0.4167L0.75 0.4167"), o),
  g.path(P("M0.25 0.5833L0.3333 0.5833 0.3333 0.8333"), o),
  g.path(P("M0.5833 0.1667L0.6667 0.1667 0.6667 0.4167"), o),
];
