// Lucide "case-lower" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCaseLower: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.4167 0.375L0.4167 0.6667"), o),
  g.path(P("M0.5833 0.25L0.5833 0.6667"), o),
  g.circle(X(0.7292), Y(0.5208), S(0.2917), o),
  g.circle(X(0.2708), Y(0.5208), S(0.2917), o),
];
