// Lucide "copyright" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCopyright: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
  g.path(
    P(
      "M0.6179 0.6179C0.5528 0.683 0.4473 0.6829 0.3823 0.6178 0.3172 0.5527 0.3172 0.4473 0.3823 0.3822 0.4473 0.3171 0.5528 0.317 0.6179 0.3821",
    ),
    o,
  ),
];
