// Lucide "copyleft" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCopyleft: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
  g.path(
    P(
      "M0.3821 0.6179C0.4472 0.683 0.5527 0.6829 0.6177 0.6178 0.6828 0.5527 0.6828 0.4473 0.6177 0.3822 0.5527 0.3171 0.4472 0.317 0.3821 0.3821",
    ),
    o,
  ),
];
