// Lucide "grid-2x2" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideGrid2x2: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.125L0.5 0.875"), o),
  g.path(P("M0.125 0.5L0.875 0.5"), o),
  g.path(
    P(
      "M0.2083 0.125L0.7917 0.125Q0.875 0.125 0.875 0.2083L0.875 0.7917Q0.875 0.875 0.7917 0.875L0.2083 0.875Q0.125 0.875 0.125 0.7917L0.125 0.2083Q0.125 0.125 0.2083 0.125Z",
    ),
    o,
  ),
];
