// Lucide "grid-2x2-x" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideGrid2x2X: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.5 0.125L0.5 0.8333C0.5 0.8563 0.4813 0.875 0.4583 0.875L0.2083 0.875C0.1623 0.875 0.125 0.8377 0.125 0.7917L0.125 0.2083C0.125 0.1623 0.1623 0.125 0.2083 0.125L0.7917 0.125C0.8377 0.125 0.875 0.1623 0.875 0.2083L0.875 0.4583C0.875 0.4813 0.8563 0.5 0.8333 0.5L0.125 0.5",
    ),
    o,
  ),
  g.path(P("M0.6875 0.6875L0.8958 0.8958"), o),
  g.path(P("M0.6875 0.8958L0.8958 0.6875"), o),
];
