// Lucide "hash" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideHash: IconDrawing = ({ g, o, X, Y }) => [
  g.line(X(0.1667), Y(0.375), X(0.8333), Y(0.375), o),
  g.line(X(0.1667), Y(0.625), X(0.8333), Y(0.625), o),
  g.line(X(0.4167), Y(0.125), X(0.3333), Y(0.875), o),
  g.line(X(0.6667), Y(0.125), X(0.5833), Y(0.875), o),
];
