// Lucide "heading" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideHeading: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.25 0.5L0.75 0.5"), o),
  g.path(P("M0.25 0.8333L0.25 0.1667"), o),
  g.path(P("M0.75 0.8333L0.75 0.1667"), o),
];
