// Lucide "heading-1" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideHeading1: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.1667 0.5L0.5 0.5"), o),
  g.path(P("M0.1667 0.75L0.1667 0.25"), o),
  g.path(P("M0.5 0.75L0.5 0.25"), o),
  g.path(P("M0.7083 0.5L0.8333 0.4167 0.8333 0.75"), o),
];
