// Lucide "heading-4" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideHeading4: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.75L0.5 0.25"), o),
  g.path(
    P(
      "M0.7083 0.4167L0.7083 0.5417C0.7083 0.5647 0.727 0.5833 0.75 0.5833L0.875 0.5833",
    ),
    o,
  ),
  g.path(P("M0.875 0.4167L0.875 0.75"), o),
  g.path(P("M0.1667 0.5L0.5 0.5"), o),
  g.path(P("M0.1667 0.75L0.1667 0.25"), o),
];
