// Lucide "library" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideLibrary: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.6667 0.25L0.8333 0.8333"), o),
  g.path(P("M0.5 0.25L0.5 0.8333"), o),
  g.path(P("M0.3333 0.3333L0.3333 0.8333"), o),
  g.path(P("M0.1667 0.1667L0.1667 0.8333"), o),
];
