// Lucide "link-2-off" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideLink2Off: IconDrawing = ({ g, o, X, Y, P }) => [
  g.path(
    P(
      "M0.375 0.7083L0.2917 0.7083C0.1766 0.7083 0.0833 0.6151 0.0833 0.5 0.0833 0.3849 0.1766 0.2917 0.2917 0.2917",
    ),
    o,
  ),
  g.path(
    P(
      "M0.625 0.2917L0.7083 0.2917C0.7872 0.2917 0.8594 0.3363 0.8947 0.4068 0.93 0.4774 0.9223 0.5619 0.875 0.625",
    ),
    o,
  ),
  g.line(X(0.3333), Y(0.5), X(0.5), Y(0.5), o),
  g.line(X(0.0833), Y(0.0833), X(0.9167), Y(0.9167), o),
];
