// Lucide "list-checks" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideListChecks: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5417 0.2083L0.875 0.2083"), o),
  g.path(P("M0.5417 0.5L0.875 0.5"), o),
  g.path(P("M0.5417 0.7917L0.875 0.7917"), o),
  g.path(P("M0.125 0.7083L0.2083 0.7917 0.375 0.625"), o),
  g.path(P("M0.125 0.2917L0.2083 0.375 0.375 0.2083"), o),
];
