// Lucide "list-indent-decrease" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideListIndentDecrease: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.875 0.2083L0.4583 0.2083"), o),
  g.path(P("M0.875 0.5L0.4583 0.5"), o),
  g.path(P("M0.875 0.7917L0.4583 0.7917"), o),
  g.path(P("M0.2917 0.3333L0.125 0.5 0.2917 0.6667"), o),
];
