// Lucide "list-collapse" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideListCollapse: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.4167 0.2083L0.875 0.2083"), o),
  g.path(P("M0.4167 0.5L0.875 0.5"), o),
  g.path(P("M0.4167 0.7917L0.875 0.7917"), o),
  g.path(P("M0.125 0.4167L0.25 0.2917 0.125 0.1667"), o),
  g.path(P("M0.125 0.8333L0.25 0.7083 0.125 0.5833"), o),
];
