// Lucide "list-chevrons-down-up" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideListChevronsDownUp: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.125 0.2083L0.4583 0.2083"), o),
  g.path(P("M0.125 0.5L0.4583 0.5"), o),
  g.path(P("M0.125 0.7917L0.4583 0.7917"), o),
  g.path(P("M0.625 0.2083L0.75 0.3333 0.875 0.2083"), o),
  g.path(P("M0.625 0.7917L0.75 0.6667 0.875 0.7917"), o),
];
