// Lucide "list-sort-descending" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideListSortDescending: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.625 0.5L0.125 0.5"), o),
  g.path(P("M0.125 0.2083L0.875 0.2083"), o),
  g.path(P("M0.375 0.7917L0.125 0.7917"), o),
];
