// Lucide "pilcrow" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucidePilcrow: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5417 0.1667L0.5417 0.8333"), o),
  g.path(P("M0.7083 0.1667L0.7083 0.8333"), o),
  g.path(
    P(
      "M0.7917 0.1667L0.3958 0.1667C0.2923 0.1667 0.2083 0.2506 0.2083 0.3542 0.2083 0.4577 0.2923 0.5417 0.3958 0.5417L0.5417 0.5417",
    ),
    o,
  ),
];
