// Lucide "redo-2" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideRedo2: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.625 0.5833L0.8333 0.375 0.625 0.1667"), o),
  g.path(
    P(
      "M0.8333 0.375L0.3958 0.375C0.2693 0.375 0.1667 0.4776 0.1667 0.6042 0.1667 0.7307 0.2693 0.8333 0.3958 0.8333L0.5417 0.8333",
    ),
    o,
  ),
];
