// Lucide "remove-formatting" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideRemoveFormatting: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.1667 0.2917L0.1667 0.1667 0.8333 0.1667 0.8333 0.2917"), o),
  g.path(P("M0.2083 0.8333L0.4583 0.8333"), o),
  g.path(P("M0.5417 0.1667L0.3333 0.8333"), o),
  g.path(P("M0.625 0.625L0.8333 0.8333"), o),
  g.path(P("M0.8333 0.625L0.625 0.8333"), o),
];
