// Lucide "save-off" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSaveOff: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.5417 0.5417L0.3333 0.5417C0.3103 0.5417 0.2917 0.5603 0.2917 0.5833L0.2917 0.875",
    ),
    o,
  ),
  g.path(P("M0.5833 0.3333L0.625 0.3333"), o),
  g.path(P("M0.7083 0.875L0.7083 0.7083"), o),
  g.path(P("M0.0833 0.0833L0.9167 0.9167"), o),
  g.path(
    P(
      "M0.8504 0.8504C0.8349 0.8661 0.8137 0.8749 0.7917 0.875L0.2083 0.875C0.1623 0.875 0.125 0.8377 0.125 0.7917L0.125 0.2083C0.1251 0.1863 0.1339 0.1651 0.1496 0.1496",
    ),
    o,
  ),
  g.path(
    P(
      "M0.375 0.125L0.6333 0.125C0.6553 0.1253 0.6763 0.1343 0.6917 0.15L0.85 0.3083C0.8657 0.3237 0.8747 0.3447 0.875 0.3667L0.875 0.625",
    ),
    o,
  ),
];
