// Lucide "scissors" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideScissors: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.25), Y(0.25), S(0.25), o),
  g.path(P("M0.3383 0.3383L0.5 0.5"), o),
  g.path(P("M0.8333 0.1667L0.3383 0.6617"), o),
  g.circle(X(0.25), Y(0.75), S(0.25), o),
  g.path(P("M0.6167 0.6167L0.8333 0.8333"), o),
];
