// Lucide "search-alert" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSearchAlert: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.4583), Y(0.4583), S(0.6667), o),
  g.path(P("M0.875 0.875L0.6958 0.6958"), o),
  g.path(P("M0.4583 0.2917L0.4583 0.4583"), o),
  g.path(P("M0.4583 0.625L0.4587 0.625"), o),
];
