// Lucide "search-code" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSearchCode: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.5417 0.5625L0.625 0.4583 0.5417 0.3542"), o),
  g.path(P("M0.875 0.875L0.6958 0.6958"), o),
  g.path(P("M0.375 0.3542L0.2917 0.4583 0.375 0.5625"), o),
  g.circle(X(0.4583), Y(0.4583), S(0.6667), o),
];
