// Lucide "separator-horizontal" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSeparatorHorizontal: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.6667 0.6667L0.5 0.8333 0.3333 0.6667"), o),
  g.path(P("M0.125 0.5L0.875 0.5"), o),
  g.path(P("M0.3333 0.3333L0.5 0.1667 0.6667 0.3333"), o),
];
