// Lucide "separator-vertical" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSeparatorVertical: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.125L0.5 0.875"), o),
  g.path(P("M0.6667 0.6667L0.8333 0.5 0.6667 0.3333"), o),
  g.path(P("M0.3333 0.3333L0.1667 0.5 0.3333 0.6667"), o),
];
