// Lucide "space" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSpace: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.9167 0.7083L0.9167 0.75C0.9167 0.7708 0.8958 0.7917 0.875 0.7917L0.125 0.7917C0.1042 0.7917 0.0833 0.7708 0.0833 0.75L0.0833 0.7083",
    ),
    o,
  ),
];
