// Lucide "spell-check" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSpellCheck: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.8333 0.625L0.6042 0.8542 0.5 0.75"), o),
  g.path(P("M0.1667 0.6667L0.4167 0.1667 0.6298 0.5929"), o),
  g.path(P("M0.25 0.5L0.5833 0.5"), o),
];
