// Lucide "table-rows-split" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTableRowsSplit: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5833 0.4167L0.6667 0.4167"), o),
  g.path(P("M0.625 0.9167L0.625 0.5833"), o),
  g.path(P("M0.625 0.0833L0.625 0.25"), o),
  g.path(P("M0.0833 0.4167L0.1667 0.4167"), o),
  g.path(P("M0.8333 0.4167L0.9167 0.4167"), o),
  g.path(P("M0.125 0.7917L0.875 0.7917"), o),
  g.path(
    P(
      "M0.125 0.9167L0.125 0.6667C0.125 0.6206 0.1623 0.5833 0.2083 0.5833L0.7917 0.5833C0.8377 0.5833 0.875 0.6206 0.875 0.6667L0.875 0.9167",
    ),
    o,
  ),
  g.path(
    P(
      "M0.125 0.0833L0.125 0.1667C0.125 0.2127 0.1623 0.25 0.2083 0.25L0.7917 0.25C0.8377 0.25 0.875 0.2127 0.875 0.1667L0.875 0.0833",
    ),
    o,
  ),
  g.path(P("M0.3333 0.4167L0.4167 0.4167"), o),
  g.path(P("M0.375 0.9167L0.375 0.5833"), o),
  g.path(P("M0.375 0.0833L0.375 0.25"), o),
];
