// Lucide "table-of-contents" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTableOfContents: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.6667 0.2083L0.125 0.2083"), o),
  g.path(P("M0.6667 0.5L0.125 0.5"), o),
  g.path(P("M0.6667 0.7917L0.125 0.7917"), o),
  g.path(P("M0.875 0.2083L0.8754 0.2083"), o),
  g.path(P("M0.875 0.5L0.8754 0.5"), o),
  g.path(P("M0.875 0.7917L0.8754 0.7917"), o),
];
