// Lucide "table-columns-split" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTableColumnsSplit: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5833 0.5833L0.5833 0.6667"), o),
  g.path(P("M0.5833 0.8333L0.5833 0.9167"), o),
  g.path(P("M0.5833 0.0833L0.5833 0.1667"), o),
  g.path(P("M0.5833 0.3333L0.5833 0.4167"), o),
  g.path(P("M0.0833 0.625L0.4167 0.625"), o),
  g.path(
    P(
      "M0.0833 0.125L0.3333 0.125C0.3794 0.125 0.4167 0.1623 0.4167 0.2083L0.4167 0.7917C0.4167 0.8377 0.3794 0.875 0.3333 0.875L0.0833 0.875",
    ),
    o,
  ),
  g.path(P("M0.0833 0.375L0.4167 0.375"), o),
  g.path(P("M0.9167 0.625L0.75 0.625"), o),
  g.path(
    P(
      "M0.9167 0.125L0.8333 0.125C0.7873 0.125 0.75 0.1623 0.75 0.2083L0.75 0.7917C0.75 0.8377 0.7873 0.875 0.8333 0.875L0.9167 0.875",
    ),
    o,
  ),
  g.path(P("M0.9167 0.375L0.75 0.375"), o),
  g.path(P("M0.2083 0.125L0.2083 0.875"), o),
];
