// Lucide "text-search" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTextSearch: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.875 0.2083L0.125 0.2083"), o),
  g.path(P("M0.4167 0.5L0.125 0.5"), o),
  g.path(P("M0.4167 0.7917L0.125 0.7917"), o),
  g.circle(X(0.7083), Y(0.625), S(0.25), o),
  g.path(P("M0.875 0.7917L0.7958 0.7125"), o),
];
