// Lucide "text-align-center" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTextAlignCenter: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.875 0.2083L0.125 0.2083"), o),
  g.path(P("M0.7083 0.5L0.2917 0.5"), o),
  g.path(P("M0.7917 0.7917L0.2083 0.7917"), o),
];
