// Lucide "underline" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideUnderline: IconDrawing = ({ g, o, X, Y, P }) => [
  g.path(
    P(
      "M0.25 0.1667L0.25 0.4167C0.25 0.5547 0.3619 0.6667 0.5 0.6667 0.6381 0.6667 0.75 0.5547 0.75 0.4167L0.75 0.1667",
    ),
    o,
  ),
  g.line(X(0.1667), Y(0.8333), X(0.8333), Y(0.8333), o),
];
