// Lucide "undo-dot" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideUndoDot: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(
    P(
      "M0.875 0.7083C0.8749 0.5605 0.7879 0.4266 0.6529 0.3663 0.518 0.306 0.3602 0.3306 0.25 0.4292L0.125 0.5417",
    ),
    o,
  ),
  g.path(P("M0.125 0.2917L0.125 0.5417 0.375 0.5417"), o),
  g.circle(X(0.5), Y(0.7083), S(0.0833), o),
];
