// Lucide "bubbles" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideBubbles: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(
    P(
      "M0.2917 0.6285C0.3108 0.6218 0.3321 0.6247 0.3486 0.6365 0.3652 0.6482 0.375 0.6672 0.375 0.6875",
    ),
    o,
  ),
  g.circle(X(0.7708), Y(0.3542), S(0.2917), o),
  g.circle(X(0.3125), Y(0.6875), S(0.4583), o),
  g.circle(X(0.3125), Y(0.1875), S(0.2083), o),
];
