// Lucide "cloud-sun-rain" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCloudSunRain: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.0833L0.5 0.1667"), o),
  g.path(P("M0.2054 0.2054L0.2642 0.2642"), o),
  g.path(P("M0.8333 0.5L0.9167 0.5"), o),
  g.path(P("M0.7946 0.2054L0.7358 0.2642"), o),
  g.path(
    P(
      "M0.6645 0.5271C0.6749 0.4637 0.648 0.3999 0.5953 0.3632 0.5426 0.3265 0.4734 0.3233 0.4176 0.3551",
    ),
    o,
  ),
  g.path(
    P(
      "M0.125 0.8333C0.0737 0.7649 0.0695 0.6721 0.1143 0.5993 0.159 0.5265 0.2438 0.4884 0.3279 0.5033 0.4121 0.5181 0.4787 0.5829 0.4958 0.6667L0.5417 0.6667C0.5936 0.6666 0.6401 0.6986 0.6586 0.7471 0.6771 0.7956 0.6638 0.8505 0.625 0.885",
    ),
    o,
  ),
  g.path(P("M0.4583 0.8333L0.4583 0.9167"), o),
  g.path(P("M0.2917 0.7917L0.2917 0.875"), o),
];
