// Lucide "snowflake" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSnowflake: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.4167 0.8333L0.3646 0.7292 0.25 0.75"), o),
  g.path(P("M0.4167 0.1667L0.3646 0.2708 0.25 0.25"), o),
  g.path(P("M0.5833 0.8333L0.6354 0.7292 0.75 0.75"), o),
  g.path(P("M0.5833 0.1667L0.6354 0.2708 0.75 0.25"), o),
  g.path(P("M0.7083 0.875L0.5833 0.625 0.4167 0.625"), o),
  g.path(P("M0.7083 0.125L0.5833 0.375 0.6458 0.5"), o),
  g.path(P("M0.0833 0.5L0.3542 0.5 0.4167 0.375"), o),
  g.path(P("M0.8333 0.4167L0.7708 0.5 0.8333 0.5833"), o),
  g.path(P("M0.9167 0.5L0.6458 0.5 0.5833 0.625"), o),
  g.path(P("M0.1667 0.4167L0.2292 0.5 0.1667 0.5833"), o),
  g.path(P("M0.2917 0.875L0.4167 0.625 0.3542 0.5"), o),
  g.path(P("M0.2917 0.125L0.4167 0.375 0.5833 0.375"), o),
];
