// Lucide "dollar-sign" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideDollarSign: IconDrawing = ({ g, o, X, Y, P }) => [
  g.line(X(0.5), Y(0.0833), X(0.5), Y(0.9167), o),
  g.path(
    P(
      "M0.7083 0.2083L0.3958 0.2083C0.3153 0.2083 0.25 0.2736 0.25 0.3542 0.25 0.4347 0.3153 0.5 0.3958 0.5L0.6042 0.5C0.6847 0.5 0.75 0.5653 0.75 0.6458 0.75 0.7264 0.6847 0.7917 0.6042 0.7917L0.25 0.7917",
    ),
    o,
  ),
];
