// Lucide "indian-rupee" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideIndianRupee: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.25 0.125L0.75 0.125"), o),
  g.path(P("M0.25 0.3333L0.75 0.3333"), o),
  g.path(P("M0.25 0.5417L0.6042 0.875"), o),
  g.path(P("M0.25 0.5417L0.375 0.5417"), o),
  g.path(P("M0.375 0.5417C0.6528 0.5417 0.6528 0.125 0.375 0.125"), o),
];
