// Lucide "japanese-yen" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideJapaneseYen: IconDrawing = ({ g, o, P }) => [
  g.path(
    P("M0.5 0.3958L0.5 0.875M0.5 0.3958L0.25 0.125M0.5 0.3958L0.75 0.125"),
    o,
  ),
  g.path(P("M0.25 0.625L0.75 0.625"), o),
  g.path(P("M0.25 0.4583L0.75 0.4583"), o),
];
