// Lucide "pound-sterling" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucidePoundSterling: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.75 0.2917C0.75 0.0695 0.4167 0.0695 0.4167 0.2917"), o),
  g.path(P("M0.4167 0.2917L0.4167 0.875"), o),
  g.path(P("M0.25 0.875L0.75 0.875"), o),
  g.path(P("M0.25 0.5417L0.6667 0.5417"), o),
];
