// Lucide "russian-ruble" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideRussianRuble: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.25 0.4583L0.5833 0.4583C0.6754 0.4583 0.75 0.3837 0.75 0.2917 0.75 0.1996 0.6754 0.125 0.5833 0.125L0.375 0.125 0.375 0.875",
    ),
    o,
  ),
  g.path(P("M0.25 0.625L0.5833 0.625"), o),
];
