// Lucide "turkish-lira" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTurkishLira: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.625 0.1667L0.2083 0.375"), o),
  g.path(P("M0.625 0.3542L0.2083 0.5625"), o),
  g.path(P("M0.75 0.5C0.75 0.7071 0.5821 0.875 0.375 0.875L0.375 0.125"), o),
];
