// Lucide "axis-3d" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideAxis3d: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5625 0.4375L0.625 0.375"), o),
  g.path(
    P(
      "M0.1667 0.1667L0.1667 0.7917C0.1667 0.8147 0.1853 0.8333 0.2083 0.8333L0.8333 0.8333",
    ),
    o,
  ),
  g.path(P("M0.1789 0.8211L0.25 0.75"), o),
  g.path(P("M0.375 0.625L0.4375 0.5625"), o),
];
