// Lucide "blend" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideBlend: IconDrawing = ({ g, o, X, Y, S }) => [
  g.circle(X(0.625), Y(0.375), S(0.5833), o),
  g.circle(X(0.375), Y(0.625), S(0.5833), o),
];
