// Lucide "frame" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideFrame: IconDrawing = ({ g, o, X, Y }) => [
  g.line(X(0.9167), Y(0.25), X(0.0833), Y(0.25), o),
  g.line(X(0.9167), Y(0.75), X(0.0833), Y(0.75), o),
  g.line(X(0.25), Y(0.0833), X(0.25), Y(0.9167), o),
  g.line(X(0.75), Y(0.0833), X(0.75), Y(0.9167), o),
];
