// Lucide "move-3d" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMove3d: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.2083 0.125L0.2083 0.7917 0.875 0.7917"), o),
  g.path(P("M0.2083 0.7917L0.4583 0.5417"), o),
  g.path(P("M0.0833 0.25L0.2083 0.125 0.3333 0.25"), o),
  g.path(P("M0.75 0.6667L0.875 0.7917 0.75 0.9167"), o),
];
