// Lucide "rotate-3d" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideRotate3d: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.6331 0.5711L0.792 0.6486 0.7145 0.8075"), o),
  g.path(
    P(
      "M0.6863 0.3137C0.638 0.1204 0.5239 0.0331 0.4235 0.1125 0.323 0.1918 0.2695 0.4116 0.3003 0.6187 0.3311 0.8257 0.4358 0.9515 0.5417 0.9082",
    ),
    o,
  ),
  g.path(
    P(
      "M0.9082 0.4583C0.8701 0.365 0.7102 0.2965 0.5199 0.2919 0.3296 0.2873 0.1573 0.3479 0.1016 0.439 0.0458 0.5301 0.1207 0.6285 0.2836 0.678 0.4464 0.7275 0.6556 0.7155 0.7917 0.6488",
    ),
    o,
  ),
];
