// Lucide "square-dashed-plus" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSquareDashedPlus: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.2083 0.125C0.1623 0.125 0.125 0.1623 0.125 0.2083"), o),
  g.path(P("M0.7917 0.125C0.8377 0.125 0.875 0.1623 0.875 0.2083"), o),
  g.path(P("M0.875 0.7917C0.875 0.8377 0.8377 0.875 0.7917 0.875"), o),
  g.path(P("M0.2083 0.875C0.1623 0.875 0.125 0.8377 0.125 0.7917"), o),
  g.path(P("M0.375 0.125L0.4167 0.125"), o),
  g.path(P("M0.375 0.875L0.4167 0.875"), o),
  g.path(P("M0.5833 0.125L0.625 0.125"), o),
  g.path(P("M0.5833 0.875L0.625 0.875"), o),
  g.path(P("M0.125 0.375L0.125 0.4167"), o),
  g.path(P("M0.875 0.375L0.875 0.4167"), o),
  g.path(P("M0.125 0.5833L0.125 0.625"), o),
  g.path(P("M0.875 0.5833L0.875 0.625"), o),
  g.path(P("M0.3333 0.5L0.6667 0.5"), o),
  g.path(P("M0.5 0.3333L0.5 0.6667"), o),
];
