// Lucide "clock-11" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideClock11: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.circle(X(0.5), Y(0.5), S(0.8333), o),
  g.path(P("M0.5 0.25L0.5 0.5 0.4167 0.3333"), o),
];
