// Lucide "hourglass-cog" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideHourglassCog: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.596 0.8137L0.6345 0.7978"), o),
  g.path(P("M0.6345 0.7022L0.596 0.6862"), o),
  g.path(P("M0.7022 0.6345L0.6862 0.596"), o),
  g.path(P("M0.7022 0.8655L0.6862 0.904"), o),
  g.path(
    P(
      "M0.7083 0.0833L0.7083 0.2572C0.7083 0.2793 0.6995 0.3005 0.6839 0.3161L0.3161 0.6839C0.3005 0.6995 0.2917 0.7207 0.2917 0.7428L0.2917 0.9167",
    ),
    o,
  ),
  g.path(P("M0.7978 0.6345L0.8138 0.596"), o),
  g.path(P("M0.8137 0.904L0.7978 0.8655"), o),
  g.path(P("M0.8655 0.7022L0.904 0.6862"), o),
  g.path(P("M0.8655 0.7978L0.904 0.8138"), o),
  g.path(P("M0.2083 0.9167L0.465 0.9167"), o),
  g.path(P("M0.2083 0.0833L0.7917 0.0833"), o),
  g.path(
    P(
      "M0.2917 0.0833L0.2917 0.2572C0.2917 0.2793 0.3005 0.3005 0.3161 0.3161L0.5323 0.5322",
    ),
    o,
  ),
  g.circle(X(0.75), Y(0.75), S(0.25), o),
];
