// Lucide "timer" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTimer: IconDrawing = ({ g, o, X, Y, S }) => [
  g.line(X(0.4167), Y(0.0833), X(0.5833), Y(0.0833), o),
  g.line(X(0.5), Y(0.5833), X(0.625), Y(0.4583), o),
  g.circle(X(0.5), Y(0.5833), S(0.6667), o),
];
