// Lucide "dna-off" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideDnaOff: IconDrawing = ({ g, o, P }) => [
  g.path(
    P("M0.625 0.0833C0.5687 0.1458 0.5378 0.2083 0.5208 0.2708L0.5833 0.3333"),
    o,
  ),
  g.path(P("M0.7083 0.25L0.5879 0.1295"), o),
  g.path(P("M0.0833 0.625C0.2222 0.5 0.3611 0.5 0.5 0.5"), o),
  g.path(P("M0.0833 0.0833L0.9167 0.9167"), o),
  g.path(P("M0.8333 0.375L0.8705 0.4121"), o),
  g.path(
    P("M0.9167 0.375C0.8542 0.4312 0.7917 0.4622 0.7292 0.4792L0.6875 0.4375"),
    o,
  ),
  g.path(P("M0.1295 0.5879L0.1667 0.625"), o),
  g.path(P("M0.2708 0.5208L0.3125 0.5625"), o),
  g.path(P("M0.2917 0.75L0.4121 0.8705"), o),
  g.path(
    P("M0.375 0.9167C0.4312 0.8542 0.4622 0.7917 0.4792 0.7292L0.4167 0.6667"),
    o,
  ),
];
