// Lucide "mars-stroke" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMarsStroke: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.5833 0.25L0.75 0.4167"), o),
  g.path(P("M0.7083 0.125L0.875 0.125 0.875 0.2917"), o),
  g.path(P("M0.875 0.125L0.5521 0.4479"), o),
  g.circle(X(0.375), Y(0.625), S(0.5), o),
];
