// Lucide "mars" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMars: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.6667 0.125L0.875 0.125 0.875 0.3333"), o),
  g.path(P("M0.875 0.125L0.5938 0.4063"), o),
  g.circle(X(0.4167), Y(0.5833), S(0.5), o),
];
