// Lucide "siren" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSiren: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.2917 0.75L0.2917 0.5C0.2917 0.3849 0.3849 0.2917 0.5 0.2917 0.6151 0.2917 0.7083 0.3849 0.7083 0.5L0.7083 0.75",
    ),
    o,
  ),
  g.path(
    P(
      "M0.2083 0.875C0.2083 0.898 0.227 0.9167 0.25 0.9167L0.75 0.9167C0.773 0.9167 0.7917 0.898 0.7917 0.875L0.7917 0.8333C0.7917 0.7873 0.7544 0.75 0.7083 0.75L0.2917 0.75C0.2456 0.75 0.2083 0.7873 0.2083 0.8333Z",
    ),
    o,
  ),
  g.path(P("M0.875 0.5L0.9167 0.5"), o),
  g.path(P("M0.7708 0.1875L0.75 0.2083"), o),
  g.path(P("M0.0833 0.5L0.125 0.5"), o),
  g.path(P("M0.5 0.0833L0.5 0.125"), o),
  g.path(P("M0.2054 0.2054L0.2348 0.2348"), o),
  g.path(P("M0.5 0.5L0.5 0.75"), o),
];
