// Lucide "venus-and-mars" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideVenusAndMars: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.4167 0.8333L0.5833 0.8333"), o),
  g.path(P("M0.5 0.6667L0.5 0.9167"), o),
  g.path(P("M0.7083 0.0833L0.875 0.0833 0.875 0.25"), o),
  g.path(P("M0.875 0.0833L0.6475 0.3108"), o),
  g.circle(X(0.5), Y(0.4583), S(0.4167), o),
];
