// Lucide "venus" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideVenus: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.5 0.625L0.5 0.9167"), o),
  g.path(P("M0.375 0.7917L0.625 0.7917"), o),
  g.circle(X(0.5), Y(0.375), S(0.5), o),
];
