// Lucide "virus" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideVirus: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.5 0.6246L0.5004 0.6246"), o),
  g.path(P("M0.5 0.9167L0.5 0.7917"), o),
  g.path(P("M0.5 0.0833L0.5 0.2083"), o),
  g.path(P("M0.5417 0.9167L0.4583 0.9167"), o),
  g.path(P("M0.5417 0.0833L0.4583 0.0833"), o),
  g.path(P("M0.5829 0.4167L0.5833 0.4167"), o),
  g.path(P("M0.6875 0.8247L0.6458 0.7525"), o),
  g.path(P("M0.6875 0.1752L0.6458 0.2474"), o),
  g.path(P("M0.8247 0.6875L0.7526 0.6458"), o),
  g.path(P("M0.8247 0.3125L0.7526 0.3542"), o),
  g.path(P("M0.0833 0.5L0.2083 0.5"), o),
  g.path(P("M0.0833 0.5417L0.0833 0.4583"), o),
  g.path(P("M0.9167 0.5L0.7917 0.5"), o),
  g.path(P("M0.9167 0.5417L0.9167 0.4583"), o),
  g.path(P("M0.1753 0.6875L0.2474 0.6458"), o),
  g.path(P("M0.1753 0.3125L0.2474 0.3542"), o),
  g.path(P("M0.3125 0.8247L0.3542 0.7525"), o),
  g.path(P("M0.3125 0.1752L0.3542 0.2474"), o),
  g.path(P("M0.375 0.5L0.3754 0.5"), o),
  g.circle(X(0.5), Y(0.5), S(0.5833), o),
];
