// Lucide "loader" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideLoader: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.0833L0.5 0.25"), o),
  g.path(P("M0.675 0.325L0.7958 0.2042"), o),
  g.path(P("M0.75 0.5L0.9167 0.5"), o),
  g.path(P("M0.675 0.675L0.7958 0.7958"), o),
  g.path(P("M0.5 0.75L0.5 0.9167"), o),
  g.path(P("M0.2042 0.7958L0.325 0.675"), o),
  g.path(P("M0.0833 0.5L0.25 0.5"), o),
  g.path(P("M0.2042 0.2042L0.325 0.325"), o),
];
