// Lucide "dice-2" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideDice2: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.2083 0.125L0.7917 0.125Q0.875 0.125 0.875 0.2083L0.875 0.7917Q0.875 0.875 0.7917 0.875L0.2083 0.875Q0.125 0.875 0.125 0.7917L0.125 0.2083Q0.125 0.125 0.2083 0.125Z",
    ),
    o,
  ),
  g.path(P("M0.625 0.375L0.6254 0.375"), o),
  g.path(P("M0.375 0.625L0.3754 0.625"), o),
];
