// Lucide "swords" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideSwords: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5417 0.7917L0.7917 0.5417"), o),
  g.path(
    P(
      "M0.6042 0.7292L0.1494 0.2744C0.1338 0.2588 0.125 0.2376 0.125 0.2155L0.125 0.125 0.2155 0.125C0.2376 0.125 0.2588 0.1338 0.2744 0.1494L0.7292 0.6042",
    ),
    o,
  ),
  g.path(
    P(
      "M0.6178 0.2572L0.7256 0.1494C0.7412 0.1338 0.7624 0.125 0.7845 0.125L0.875 0.125 0.875 0.2155C0.875 0.2376 0.8662 0.2588 0.8506 0.2744L0.7428 0.3822",
    ),
    o,
  ),
  g.path(P("M0.6667 0.6667L0.8333 0.8333"), o),
  g.path(P("M0.7917 0.875L0.875 0.7917"), o),
  g.path(P("M0.2083 0.5833L0.375 0.75"), o),
  g.path(P("M0.2083 0.875L0.125 0.7917"), o),
  g.path(P("M0.3125 0.6875L0.1667 0.8333"), o),
];
