// Lucide "tic-tac-toe" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideTicTacToe: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.5 0.0833L0.5 0.9167"), o),
  g.path(P("M0.875 0.6667L0.6667 0.875"), o),
  g.path(P("M0.875 0.875L0.6667 0.6667"), o),
  g.path(P("M0.9167 0.5L0.0833 0.5"), o),
  g.path(P("M0.3333 0.125L0.125 0.3333"), o),
  g.path(P("M0.3333 0.3333L0.125 0.125"), o),
  g.circle(X(0.7708), Y(0.2292), S(0.2083), o),
  g.circle(X(0.2292), Y(0.7708), S(0.2083), o),
];
