// Lucide "arrow-right-from-line" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideArrowRightFromLine: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.125 0.2083L0.125 0.7917"), o),
  g.path(P("M0.875 0.5L0.2917 0.5"), o),
  g.path(P("M0.625 0.75L0.875 0.5 0.625 0.25"), o),
];
