// Lucide "arrow-left-from-line" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideArrowLeftFromLine: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.375 0.25L0.125 0.5 0.375 0.75"), o),
  g.path(P("M0.125 0.5L0.7083 0.5"), o),
  g.path(P("M0.875 0.7917L0.875 0.2083"), o),
];
