// Lucide "arrow-up" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideArrowUp: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.2083 0.5L0.5 0.2083 0.7917 0.5"), o),
  g.path(P("M0.5 0.7917L0.5 0.2083"), o),
];
