// Lucide "arrows-up-from-line" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideArrowsUpFromLine: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.1667 0.25L0.2917 0.125 0.4167 0.25"), o),
  g.path(P("M0.2917 0.7083L0.2917 0.125"), o),
  g.path(P("M0.5833 0.25L0.7083 0.125 0.8333 0.25"), o),
  g.path(P("M0.7083 0.7083L0.7083 0.125"), o),
  g.path(P("M0.1667 0.875L0.8333 0.875"), o),
];
