// Lucide "arrow-up-to-line" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideArrowUpToLine: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.2083 0.125L0.7917 0.125"), o),
  g.path(P("M0.75 0.5417L0.5 0.2917 0.25 0.5417"), o),
  g.path(P("M0.5 0.2917L0.5 0.875"), o),
];
