// Lucide "arrow-up-right" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideArrowUpRight: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.2917 0.2917L0.7083 0.2917 0.7083 0.7083"), o),
  g.path(P("M0.2917 0.7083L0.7083 0.2917"), o),
];
