// Lucide "arrow-up-from-dot" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideArrowUpFromDot: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.2083 0.375L0.5 0.0833 0.7917 0.375"), o),
  g.path(P("M0.5 0.6667L0.5 0.0833"), o),
  g.circle(X(0.5), Y(0.875), S(0.0833), o),
];
