// Lucide "arrow-down-from-line" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideArrowDownFromLine: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.7917 0.125L0.2083 0.125"), o),
  g.path(P("M0.5 0.875L0.5 0.2917"), o),
  g.path(P("M0.25 0.625L0.5 0.875 0.75 0.625"), o),
];
