// Lucide "arrow-right-left" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideArrowRightLeft: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.6667 0.125L0.8333 0.2917 0.6667 0.4583"), o),
  g.path(P("M0.8333 0.2917L0.1667 0.2917"), o),
  g.path(P("M0.3333 0.875L0.1667 0.7083 0.3333 0.5417"), o),
  g.path(P("M0.1667 0.7083L0.8333 0.7083"), o),
];
