// Lucide "arrow-down-to-line" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideArrowDownToLine: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.7083L0.5 0.125"), o),
  g.path(P("M0.25 0.4583L0.5 0.7083 0.75 0.4583"), o),
  g.path(P("M0.7917 0.875L0.2083 0.875"), o),
];
