// Lucide "arrow-up-down" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideArrowUpDown: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.875 0.6667L0.7083 0.8333 0.5417 0.6667"), o),
  g.path(P("M0.7083 0.8333L0.7083 0.1667"), o),
  g.path(P("M0.125 0.3333L0.2917 0.1667 0.4583 0.3333"), o),
  g.path(P("M0.2917 0.1667L0.2917 0.8333"), o),
];
