// Lucide "chevrons-left" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideChevronsLeft: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.4583 0.7083L0.25 0.5 0.4583 0.2917"), o),
  g.path(P("M0.75 0.7083L0.5417 0.5 0.75 0.2917"), o),
];
