// Lucide "chevrons-up" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideChevronsUp: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.7083 0.4583L0.5 0.25 0.2917 0.4583"), o),
  g.path(P("M0.7083 0.75L0.5 0.5417 0.2917 0.75"), o),
];
