// Lucide "chevron-first" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideChevronFirst: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.7083 0.75L0.4583 0.5 0.7083 0.25"), o),
  g.path(P("M0.2917 0.25L0.2917 0.75"), o),
];
