// Lucide "chevrons-down-up" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideChevronsDownUp: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.2917 0.8333L0.5 0.625 0.7083 0.8333"), o),
  g.path(P("M0.2917 0.1667L0.5 0.375 0.7083 0.1667"), o),
];
