// Lucide "chevrons-left-right" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideChevronsLeftRight: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.375 0.2917L0.1667 0.5 0.375 0.7083"), o),
  g.path(P("M0.625 0.2917L0.8333 0.5 0.625 0.7083"), o),
];
