// Lucide "chevron-right" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideChevronRight: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.375 0.75L0.625 0.5 0.375 0.25"), o),
];
