// Lucide "chevrons-right-left" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideChevronsRightLeft: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.8333 0.7083L0.625 0.5 0.8333 0.2917"), o),
  g.path(P("M0.1667 0.7083L0.375 0.5 0.1667 0.2917"), o),
];
