// Lucide "chevrons-down" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideChevronsDown: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.2917 0.25L0.5 0.4583 0.7083 0.25"), o),
  g.path(P("M0.2917 0.5417L0.5 0.75 0.7083 0.5417"), o),
];
