// Lucide "chevrons-up-down" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideChevronsUpDown: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.2917 0.625L0.5 0.8333 0.7083 0.625"), o),
  g.path(P("M0.2917 0.375L0.5 0.1667 0.7083 0.375"), o),
];
