// Lucide "chevron-down" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideChevronDown: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.25 0.375L0.5 0.625 0.75 0.375"), o),
];
