// Lucide "corner-left-up" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCornerLeftUp: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5833 0.375L0.375 0.1667 0.1667 0.375"), o),
  g.path(
    P(
      "M0.8333 0.8333L0.5417 0.8333C0.4496 0.8333 0.375 0.7587 0.375 0.6667L0.375 0.1667",
    ),
    o,
  ),
];
