// Lucide "corner-left-down" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCornerLeftDown: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5833 0.625L0.375 0.8333 0.1667 0.625"), o),
  g.path(
    P(
      "M0.8333 0.1667L0.5417 0.1667C0.4496 0.1667 0.375 0.2413 0.375 0.3333L0.375 0.8333",
    ),
    o,
  ),
];
