// Lucide "corner-up-left" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCornerUpLeft: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.8333 0.8333L0.8333 0.5417C0.8333 0.4496 0.7587 0.375 0.6667 0.375L0.1667 0.375",
    ),
    o,
  ),
  g.path(P("M0.375 0.5833L0.1667 0.375 0.375 0.1667"), o),
];
