// Lucide "corner-down-right" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCornerDownRight: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.625 0.4167L0.8333 0.625 0.625 0.8333"), o),
  g.path(
    P(
      "M0.1667 0.1667L0.1667 0.4583C0.1667 0.5504 0.2413 0.625 0.3333 0.625L0.8333 0.625",
    ),
    o,
  ),
];
