// Lucide "corner-down-left" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideCornerDownLeft: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.8333 0.1667L0.8333 0.4583C0.8333 0.5504 0.7587 0.625 0.6667 0.625L0.1667 0.625",
    ),
    o,
  ),
  g.path(P("M0.375 0.4167L0.1667 0.625 0.375 0.8333"), o),
];
