// Lucide "fold-vertical" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideFoldVertical: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.9167L0.5 0.6667"), o),
  g.path(P("M0.5 0.3333L0.5 0.0833"), o),
  g.path(P("M0.1667 0.5L0.0833 0.5"), o),
  g.path(P("M0.4167 0.5L0.3333 0.5"), o),
  g.path(P("M0.6667 0.5L0.5833 0.5"), o),
  g.path(P("M0.9167 0.5L0.8333 0.5"), o),
  g.path(P("M0.625 0.7917L0.5 0.6667 0.375 0.7917"), o),
  g.path(P("M0.625 0.2083L0.5 0.3333 0.375 0.2083"), o),
];
