// Lucide "iteration-cw" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideIterationCw: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.1667 0.4167C0.1667 0.2326 0.3159 0.0833 0.5 0.0833 0.6841 0.0833 0.8333 0.2326 0.8333 0.4167 0.8333 0.6008 0.6841 0.75 0.5 0.75L0.1667 0.75",
    ),
    o,
  ),
  g.path(P("M0.3333 0.9167L0.1667 0.75 0.3333 0.5833"), o),
];
