// Lucide "maximize-2" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMaximize2: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.625 0.125L0.875 0.125 0.875 0.375"), o),
  g.path(P("M0.875 0.125L0.5833 0.4167"), o),
  g.path(P("M0.125 0.875L0.4167 0.5833"), o),
  g.path(P("M0.375 0.875L0.125 0.875 0.125 0.625"), o),
];
