// Lucide "minimize-2" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMinimize2: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5833 0.4167L0.875 0.125"), o),
  g.path(P("M0.8333 0.4167L0.5833 0.4167 0.5833 0.1667"), o),
  g.path(P("M0.125 0.875L0.4167 0.5833"), o),
  g.path(P("M0.1667 0.5833L0.4167 0.5833 0.4167 0.8333"), o),
];
