// Lucide "move" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMove: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.0833L0.5 0.9167"), o),
  g.path(P("M0.625 0.7917L0.5 0.9167 0.375 0.7917"), o),
  g.path(P("M0.7917 0.375L0.9167 0.5 0.7917 0.625"), o),
  g.path(P("M0.0833 0.5L0.9167 0.5"), o),
  g.path(P("M0.2083 0.375L0.0833 0.5 0.2083 0.625"), o),
  g.path(P("M0.375 0.2083L0.5 0.0833 0.625 0.2083"), o),
];
