// Lucide "move-diagonal-2" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMoveDiagonal2: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.7917 0.5417L0.7917 0.7917 0.5417 0.7917"), o),
  g.path(P("M0.2083 0.4583L0.2083 0.2083 0.4583 0.2083"), o),
  g.path(P("M0.2083 0.2083L0.7917 0.7917"), o),
];
