// Lucide "move-left" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMoveLeft: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.25 0.3333L0.0833 0.5 0.25 0.6667"), o),
  g.path(P("M0.0833 0.5L0.9167 0.5"), o),
];
