// Lucide "move-down" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMoveDown: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.3333 0.75L0.5 0.9167 0.6667 0.75"), o),
  g.path(P("M0.5 0.0833L0.5 0.9167"), o),
];
