// Lucide "move-down-left" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideMoveDownLeft: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.4583 0.7917L0.2083 0.7917 0.2083 0.5417"), o),
  g.path(P("M0.7917 0.2083L0.2083 0.7917"), o),
];
