// Lucide "refresh-cw-off" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideRefreshCwOff: IconDrawing = ({ g, o, P }) => [
  g.path(
    P(
      "M0.875 0.3333L0.7808 0.2392C0.7055 0.1663 0.6048 0.1254 0.5 0.125 0.4583 0.125 0.4179 0.1317 0.3804 0.1446",
    ),
    o,
  ),
  g.path(P("M0.3333 0.6667L0.125 0.6667 0.125 0.875"), o),
  g.path(P("M0.125 0.5C0.125 0.3962 0.1667 0.3025 0.235 0.235"), o),
  g.path(
    P(
      "M0.125 0.6667L0.2192 0.7608C0.2945 0.8337 0.3952 0.8746 0.5 0.875 0.6038 0.875 0.6975 0.8333 0.765 0.765",
    ),
    o,
  ),
  g.path(P("M0.875 0.5C0.875 0.5417 0.8683 0.5821 0.8554 0.6196"), o),
  g.path(P("M0.875 0.125L0.875 0.3333 0.6667 0.3333"), o),
  g.path(P("M0.9167 0.9167L0.0833 0.0833"), o),
];
