// Lucide "upload" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideUpload: IconDrawing = ({ g, o, P }) => [
  g.path(P("M0.5 0.125L0.5 0.625"), o),
  g.path(P("M0.7083 0.3333L0.5 0.125 0.2917 0.3333"), o),
  g.path(
    P(
      "M0.875 0.625L0.875 0.7917C0.875 0.8377 0.8377 0.875 0.7917 0.875L0.2083 0.875C0.1623 0.875 0.125 0.8377 0.125 0.7917L0.125 0.625",
    ),
    o,
  ),
];
