// Lucide "key" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideKey: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(P("M0.0833 0.875L0.4833 0.475"), o),
  g.path(
    P(
      "M0.3125 0.6458L0.4083 0.7417C0.4242 0.7579 0.4242 0.7838 0.4083 0.8L0.3208 0.8875C0.3046 0.9034 0.2787 0.9034 0.2625 0.8875L0.1667 0.7917",
    ),
    o,
  ),
  g.circle(X(0.6458), Y(0.3125), S(0.4583), o),
];
