// Lucide "vault" (ISC licence, see ../LICENSE). Generated by
// icon-tools/convert.mjs from lucide-static 1.49.0; do not edit.
import type { IconDrawing } from "../../types";

export const lucideVault: IconDrawing = ({ g, o, X, Y, S, P }) => [
  g.path(
    P(
      "M0.2083 0.125L0.7917 0.125Q0.875 0.125 0.875 0.2083L0.875 0.7917Q0.875 0.875 0.7917 0.875L0.2083 0.875Q0.125 0.875 0.125 0.7917L0.125 0.2083Q0.125 0.125 0.2083 0.125Z",
    ),
    o,
  ),
  g.circle(X(0.3125), Y(0.3125), S(0.0417), o),
  g.path(P("M0.3292 0.3292L0.4417 0.4417"), o),
  g.circle(X(0.6875), Y(0.3125), S(0.0417), o),
  g.path(P("M0.5583 0.4417L0.6708 0.3292"), o),
  g.circle(X(0.3125), Y(0.6875), S(0.0417), o),
  g.path(P("M0.3292 0.6708L0.4417 0.5583"), o),
  g.circle(X(0.6875), Y(0.6875), S(0.0417), o),
  g.path(P("M0.5583 0.5583L0.6708 0.6708"), o),
  g.circle(X(0.5), Y(0.5), S(0.1667), o),
];
